//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {CapitalOs} from './capitalOs';
import {CapitalOsService} from './capitalOs.service';

@Component({
    moduleId: module.id,
	templateUrl: 'capitalOs-detail.component.html',
	selector: 'capitalOs-detail',
})
export class CapitalOsDetailComponent implements OnInit, OnDestroy {
    capitalOs : CapitalOs;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<CapitalOs>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private capitalOsService: CapitalOsService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for capitalOs-detail ' + id);

            if (id === 'new') {
                this.capitalOs = new CapitalOs();
            } else {
                this.capitalOsService.getCapitalOs(id)
                    .subscribe(capitalOs => {
                            this.capitalOs = capitalOs;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.capitalOsService.update(this.capitalOs).
            subscribe(
                capitalOs => {
                    this.capitalOs = capitalOs;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.capitalOs);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
