//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class CapitalOs {
    // Raw attributes
    id : number;
    ident : string;
    name : string;
    projectId : number;
    versionId : number;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.ident = json.ident;
            this.name = json.name;
            this.projectId = json.projectId;
            this.versionId = json.versionId;
        }
    }

    // Utils

    static toArray(jsons : any[]) : CapitalOs[] {
        let capitalOss : CapitalOs[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                capitalOss.push(new CapitalOs(json));
            }
        }
        return capitalOss;
    }
}
