//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { CapitalOs } from './capitalOs';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class CapitalOsService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a CapitalOs by id.
     */
    getCapitalOs(id : any) : Observable<CapitalOs> {
        return this.http.get('/api/capitalOss/' + id)
            .pipe(
                map(response => new CapitalOs(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed capitalOs.
     */
    update(capitalOs : CapitalOs) : Observable<CapitalOs> {
        let body = capitalOs;

        return this.http.put('/api/capitalOss/', body)
            .pipe(
                map(response => new CapitalOs(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of CapitalOs using the passed
     * capitalOs as an example for the search by example facility.
     */
    getPage(capitalOs : CapitalOs, event : LazyLoadEvent) : Observable<PageResponse<CapitalOs>> {
        let req = new PageRequestByExample(capitalOs, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/capitalOss/page', body)
            .pipe(
                map(pr =>  new PageResponse<CapitalOs>(pr.totalPages, pr.totalElements, CapitalOs.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by CapitalOsCompleteComponent.
     */
    complete(query : string) : Observable<CapitalOs[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/capitalOss/complete', body)
            .pipe(
                map(response => CapitalOs.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an CapitalOs by id.
     */
    delete(id : any) {
        return this.http.delete('/api/capitalOss/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
