//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { JiraStates } from './jiraStates';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class JiraStatesService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a JiraStates by id.
     */
    getJiraStates(id : any) : Observable<JiraStates> {
        return this.http.get('/api/jiraStatess/' + id)
            .pipe(
                map(response => new JiraStates(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed jiraStates.
     */
    update(jiraStates : JiraStates) : Observable<JiraStates> {
        let body = jiraStates;

        return this.http.put('/api/jiraStatess/', body)
            .pipe(
                map(response => new JiraStates(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of JiraStates using the passed
     * jiraStates as an example for the search by example facility.
     */
    getPage(jiraStates : JiraStates, event : LazyLoadEvent) : Observable<PageResponse<JiraStates>> {
        let req = new PageRequestByExample(jiraStates, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/jiraStatess/page', body)
            .pipe(
                map(pr =>  new PageResponse<JiraStates>(pr.totalPages, pr.totalElements, JiraStates.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by JiraStatesCompleteComponent.
     */
    complete(query : string) : Observable<JiraStates[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/jiraStatess/complete', body)
            .pipe(
                map(response => JiraStates.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an JiraStates by id.
     */
    delete(id : any) {
        return this.http.delete('/api/jiraStatess/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
