//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class JiraStates {
    // Raw attributes
    id : number;
    gismoState : string;
    jiraState : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.gismoState = json.gismoState;
            this.jiraState = json.jiraState;
        }
    }

    // Utils

    static toArray(jsons : any[]) : JiraStates[] {
        let jiraStatess : JiraStates[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                jiraStatess.push(new JiraStates(json));
            }
        }
        return jiraStatess;
    }
}
