//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-line.component.ts.e.vm
//
import {Component, Input} from '@angular/core';
import {CapitalSubtype} from './capitalSubtype';

@Component({
	template: `
        {{ capitalSubtype?.capitalsubtype2 }} 	`,
	selector: 'capitalSubtype-line',
})
export class CapitalSubtypeLineComponent {
    @Input() capitalSubtype : CapitalSubtype;
}
