//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class CapitalSubtype {
    // Raw attributes
    id : number;
    capitalsubtype2 : string;
    capitalitem : string;
    projectId : number;
    tasktypeid : number;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.capitalsubtype2 = json.capitalsubtype2;
            this.capitalitem = json.capitalitem;
            this.projectId = json.projectId;
            this.tasktypeid = json.tasktypeid;
        }
    }

    // Utils

    static toArray(jsons : any[]) : CapitalSubtype[] {
        let capitalSubtypes : CapitalSubtype[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                capitalSubtypes.push(new CapitalSubtype(json));
            }
        }
        return capitalSubtypes;
    }
}
