//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Project {
    // Raw attributes
    id : number;
    name : string;
    projectGroupId : number;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.name = json.name;
            this.projectGroupId = json.projectGroupId;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Project[] {
        let projects : Project[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                projects.push(new Project(json));
            }
        }
        return projects;
    }
}
