
--
-- Index pour les tables déchargées
--

--
-- Index pour la table CAPITAL_IMPUTATION
--
ALTER TABLE CAPITAL_IMPUTATION
  ADD PRIMARY KEY (id);

--
-- Index pour la table CAPITAL_ITEM
--
ALTER TABLE CAPITAL_ITEM
  ADD PRIMARY KEY (id);

--
-- Index pour la table CAPITAL_OS
--
ALTER TABLE CAPITAL_OS
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY ident (ident),
  ADD UNIQUE KEY name (name);

--
-- Index pour la table CAPITAL_SUBTYPE
--
ALTER TABLE CAPITAL_SUBTYPE
  ADD PRIMARY KEY (id);

--
-- Index pour la table GISMO_IMPUTATION
--
ALTER TABLE GISMO_IMPUTATION
  ADD PRIMARY KEY (id),
  ADD KEY task_id (task_id),
  ADD KEY user_id (user_id);

--
-- Index pour la table GISMO_USER
--
ALTER TABLE GISMO_USER
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY trigramme (trigramme);

--
-- Index pour la table JIRA_STATES
--
ALTER TABLE JIRA_STATES
  ADD PRIMARY KEY (id);

--
-- Index pour la table JIRA_TASK
--
ALTER TABLE JIRA_TASK
  ADD PRIMARY KEY (id);

--
-- Index pour la table JIRA_TASK_TYPE
--
ALTER TABLE JIRA_TASK_TYPE
  ADD PRIMARY KEY (id),
  ADD KEY task_type_id (task_type_id);

--
-- Index pour la table PROFIL
--
ALTER TABLE PROFIL
  ADD PRIMARY KEY (id),
  ADD KEY PROFIL_ibfk_1 (project_group_id),
  ADD KEY PROFIL_ibfk_2 (user_id),
  ADD KEY project_id (project_id);

--
-- Index pour la table PROJECT
--
ALTER TABLE PROJECT
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY name (name),
  ADD KEY project_group_id (project_group_id);

--
-- Index pour la table PROJECT_GROUP
--
ALTER TABLE PROJECT_GROUP
  ADD PRIMARY KEY (id);

--
-- Index pour la table SUB_PROJECT
--
ALTER TABLE SUB_PROJECT
  ADD PRIMARY KEY (id),
  ADD KEY project_id (project_id);

--
-- Index pour la table SUB_VERSION
--
ALTER TABLE SUB_VERSION
  ADD PRIMARY KEY (id),
  ADD KEY sub_project_id (sub_project_id),
  ADD KEY version_id (version_id);

--
-- Index pour la table TASK
--
ALTER TABLE TASK
  ADD PRIMARY KEY (id),
  ADD KEY task_type_id (task_type_id),
  ADD KEY projectId (project_Id),
  ADD KEY subVersion_Id (sub_version_Id),
  ADD KEY version_id (version_id),
  ADD KEY TASK_ibfk_2 (sub_project_id);

--
-- Index pour la table TASK_LINK
--
ALTER TABLE TASK_LINK
  ADD PRIMARY KEY (child_task_id,parent_task_id),
  ADD KEY child_task_id (child_task_id),
  ADD KEY parent_task_id (parent_task_id);

--
-- Index pour la table TASK_TYPE
--
ALTER TABLE TASK_TYPE
  ADD PRIMARY KEY (id),
  ADD KEY TASK_TYPE_ibfk_1 (project_id);

--
-- Index pour la table `VERSION`
--
ALTER TABLE `VERSION`
  ADD PRIMARY KEY (id),
  ADD KEY project_id (project_id);

--
-- Index pour la table WEEK_NUMBER
--
ALTER TABLE WEEK_NUMBER
  ADD PRIMARY KEY (id);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table CAPITAL_IMPUTATION
--
ALTER TABLE CAPITAL_IMPUTATION
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table CAPITAL_ITEM
--
ALTER TABLE CAPITAL_ITEM
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table CAPITAL_OS
--
ALTER TABLE CAPITAL_OS
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table CAPITAL_SUBTYPE
--
ALTER TABLE CAPITAL_SUBTYPE
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table GISMO_IMPUTATION
--
ALTER TABLE GISMO_IMPUTATION
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table JIRA_STATES
--
ALTER TABLE JIRA_STATES
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table JIRA_TASK
--
ALTER TABLE JIRA_TASK
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table JIRA_TASK_TYPE
--
ALTER TABLE JIRA_TASK_TYPE
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table PROFIL
--
ALTER TABLE PROFIL
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table SUB_VERSION
--
ALTER TABLE SUB_VERSION
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table TASK
--
ALTER TABLE TASK
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table TASK_TYPE
--
ALTER TABLE TASK_TYPE
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `VERSION`
--
ALTER TABLE `VERSION`
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table WEEK_NUMBER
--
ALTER TABLE WEEK_NUMBER
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table GISMO_IMPUTATION
--
ALTER TABLE GISMO_IMPUTATION
  ADD CONSTRAINT GISMO_IMPUTATION_ibfk_1 FOREIGN KEY (task_id) REFERENCES TASK (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT GISMO_IMPUTATION_ibfk_2 FOREIGN KEY (user_id) REFERENCES GISMO_USER (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table JIRA_TASK_TYPE
--
ALTER TABLE JIRA_TASK_TYPE
  ADD CONSTRAINT JIRA_TASK_TYPE_ibfk_1 FOREIGN KEY (task_type_id) REFERENCES TASK_TYPE (id) ON DELETE SET NULL ON UPDATE NO ACTION;

--
-- Contraintes pour la table PROFIL
--
ALTER TABLE PROFIL
  ADD CONSTRAINT PROFIL_ibfk_1 FOREIGN KEY (project_group_id) REFERENCES PROJECT_GROUP (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT PROFIL_ibfk_2 FOREIGN KEY (user_id) REFERENCES GISMO_USER (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT PROFIL_ibfk_3 FOREIGN KEY (project_id) REFERENCES PROJECT (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table PROJECT
--
ALTER TABLE PROJECT
  ADD CONSTRAINT PROJECT_ibfk_1 FOREIGN KEY (project_group_id) REFERENCES PROJECT_GROUP (id);

--
-- Contraintes pour la table SUB_PROJECT
--
ALTER TABLE SUB_PROJECT
  ADD CONSTRAINT SUB_PROJECT_ibfk_1 FOREIGN KEY (project_id) REFERENCES PROJECT (id);

--
-- Contraintes pour la table SUB_VERSION
--
ALTER TABLE SUB_VERSION
  ADD CONSTRAINT SUB_VERSION_ibfk_1 FOREIGN KEY (sub_project_id) REFERENCES SUB_PROJECT (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table TASK
--
ALTER TABLE TASK
  ADD CONSTRAINT TASK_ibfk_2 FOREIGN KEY (sub_project_id) REFERENCES SUB_PROJECT (id) ON UPDATE NO ACTION,
  ADD CONSTRAINT TASK_ibfk_3 FOREIGN KEY (version_id) REFERENCES VERSION (id) ON UPDATE NO ACTION,
  ADD CONSTRAINT TASK_ibfk_4 FOREIGN KEY (task_type_id) REFERENCES TASK_TYPE (id) ON UPDATE NO ACTION,
  ADD CONSTRAINT TASK_ibfk_5 FOREIGN KEY (sub_version_Id) REFERENCES SUB_VERSION (id) ON UPDATE NO ACTION,
  ADD CONSTRAINT TASK_ibfk_6 FOREIGN KEY (project_Id) REFERENCES PROJECT (id) ON UPDATE NO ACTION;

--
-- Contraintes pour la table TASK_LINK
--
ALTER TABLE TASK_LINK
  ADD CONSTRAINT TASK_LINK_ibfk_1 FOREIGN KEY (parent_task_id) REFERENCES TASK (id) ON DELETE CASCADE ON UPDATE NO ACTION,
  ADD CONSTRAINT TASK_LINK_ibfk_2 FOREIGN KEY (child_task_id) REFERENCES TASK (id) ON DELETE CASCADE ON UPDATE NO ACTION;

--
-- Contraintes pour la table TASK_TYPE
--
ALTER TABLE TASK_TYPE
  ADD CONSTRAINT TASK_TYPE_ibfk_1 FOREIGN KEY (project_id) REFERENCES PROJECT (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `VERSION`
--
ALTER TABLE `VERSION`
  ADD CONSTRAINT VERSION_ibfk_1 FOREIGN KEY (project_id) REFERENCES PROJECT (id);
