
-- --------------------------------------------------------

--
-- Structure de la vue TASK_PROJ
--
DROP TABLE IF EXISTS `TASK_PROJ`;

CREATE ALGORITHM=UNDEFINED DEFINER=id4490645_lbarre@`%` SQL SECURITY DEFINER VIEW TASK_PROJ  AS  select PROJECTS.GRP_ID AS GRP_ID,PROJECTS.GRP_NAME AS GRP_NAME,PROJECTS.PROJ_NAME AS PROJ_NAME,PROJECTS.VERS_NAME AS VERS_NAME,PROJECTS.SUBPRJ_NAME AS SUBPRJ_NAME,PROJECTS.SUBVERS_NAME AS SUBVERS_NAME,TASK.`id` AS TASK_ID,TASK.`name` AS TASK_NAME,TASK_TYPE.`name` AS TYPE_NAME from ((PROJECTS join TASK_TYPE) join TASK) where ((TASK.task_type_id = TASK_TYPE.`id`) and (TASK.sub_project_id = PROJECTS.SUBPRJ_ID) and (TASK.version_id = PROJECTS.VERS_ID)) ;
