//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { ProjectGroup } from './projectGroup';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class ProjectGroupService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a ProjectGroup by id.
     */
    getProjectGroup(id : any) : Observable<ProjectGroup> {
        return this.http.get('/api/projectGroups/' + id)
            .pipe(
                map(response => new ProjectGroup(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed projectGroup.
     */
    update(projectGroup : ProjectGroup) : Observable<ProjectGroup> {
        let body = projectGroup;

        return this.http.put('/api/projectGroups/', body)
            .pipe(
                map(response => new ProjectGroup(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of ProjectGroup using the passed
     * projectGroup as an example for the search by example facility.
     */
    getPage(projectGroup : ProjectGroup, event : LazyLoadEvent) : Observable<PageResponse<ProjectGroup>> {
        let req = new PageRequestByExample(projectGroup, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/projectGroups/page', body)
            .pipe(
                map(pr =>  new PageResponse<ProjectGroup>(pr.totalPages, pr.totalElements, ProjectGroup.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by ProjectGroupCompleteComponent.
     */
    complete(query : string) : Observable<ProjectGroup[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/projectGroups/complete', body)
            .pipe(
                map(response => ProjectGroup.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an ProjectGroup by id.
     */
    delete(id : any) {
        return this.http.delete('/api/projectGroups/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
