//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {ProjectGroup} from './projectGroup';
import {ProjectGroupService} from './projectGroup.service';

@Component({
    moduleId: module.id,
	templateUrl: 'projectGroup-detail.component.html',
	selector: 'projectGroup-detail',
})
export class ProjectGroupDetailComponent implements OnInit, OnDestroy {
    projectGroup : ProjectGroup;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<ProjectGroup>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private projectGroupService: ProjectGroupService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for projectGroup-detail ' + id);

            if (id === 'new') {
                this.projectGroup = new ProjectGroup();
            } else {
                this.projectGroupService.getProjectGroup(id)
                    .subscribe(projectGroup => {
                            this.projectGroup = projectGroup;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.projectGroupService.update(this.projectGroup).
            subscribe(
                projectGroup => {
                    this.projectGroup = projectGroup;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.projectGroup);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
