//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/app.module.ts.p.vm
//
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule  }  from '@angular/router';
import { MatDatepickerModule, MatNativeDateModule, MatDialogModule, MatCardModule, MatIconModule, MatSelectModule, MatTabsModule, MatInputModule, MatButtonModule } from '@angular/material';
import { ConfirmDialogModule, FileUploadModule, PanelModule, GrowlModule, MenubarModule, DialogModule, ButtonModule, AutoCompleteModule, DataTableModule, SharedModule, DropdownModule,PickListModule,CheckboxModule,TriStateCheckboxModule, InputTextModule,InputTextareaModule,CalendarModule,PasswordModule,TabViewModule } from 'primeng/primeng';
import { ConfirmationService } from 'primeng/primeng';
import { AppComponent }   from './app.component';
import { HomeComponent }  from './home.component';
import { AuthService } from './service/auth.service';
import { MessageService } from './service/message.service';
import { routing }        from './app.routes';
import { EmailValidator } from './support/email.validator';
import { ConfirmDeleteDialogComponent } from './support/confirm-delete-dialog.component';


// CapitalImputation ...
import { CapitalImputationService } from './entities/capitalImputation/capitalImputation.service';
import { CapitalImputationListComponent } from './entities/capitalImputation/capitalImputation-list.component';
import { CapitalImputationDetailComponent } from './entities/capitalImputation/capitalImputation-detail.component';
import { CapitalImputationLineComponent } from './entities/capitalImputation/capitalImputation-line.component';
import { CapitalImputationCompleteComponent } from './entities/capitalImputation/capitalImputation-auto-complete.component';

// CapitalItem ...
import { CapitalItemService } from './entities/capitalItem/capitalItem.service';
import { CapitalItemListComponent } from './entities/capitalItem/capitalItem-list.component';
import { CapitalItemDetailComponent } from './entities/capitalItem/capitalItem-detail.component';
import { CapitalItemLineComponent } from './entities/capitalItem/capitalItem-line.component';
import { CapitalItemCompleteComponent } from './entities/capitalItem/capitalItem-auto-complete.component';

// CapitalOs ...
import { CapitalOsService } from './entities/capitalOs/capitalOs.service';
import { CapitalOsListComponent } from './entities/capitalOs/capitalOs-list.component';
import { CapitalOsDetailComponent } from './entities/capitalOs/capitalOs-detail.component';
import { CapitalOsLineComponent } from './entities/capitalOs/capitalOs-line.component';
import { CapitalOsCompleteComponent } from './entities/capitalOs/capitalOs-auto-complete.component';

// CapitalSubtype ...
import { CapitalSubtypeService } from './entities/capitalSubtype/capitalSubtype.service';
import { CapitalSubtypeListComponent } from './entities/capitalSubtype/capitalSubtype-list.component';
import { CapitalSubtypeDetailComponent } from './entities/capitalSubtype/capitalSubtype-detail.component';
import { CapitalSubtypeLineComponent } from './entities/capitalSubtype/capitalSubtype-line.component';
import { CapitalSubtypeCompleteComponent } from './entities/capitalSubtype/capitalSubtype-auto-complete.component';

// GismoImputation ...
import { GismoImputationService } from './entities/gismoImputation/gismoImputation.service';
import { GismoImputationListComponent } from './entities/gismoImputation/gismoImputation-list.component';
import { GismoImputationDetailComponent } from './entities/gismoImputation/gismoImputation-detail.component';
import { GismoImputationLineComponent } from './entities/gismoImputation/gismoImputation-line.component';
import { GismoImputationCompleteComponent } from './entities/gismoImputation/gismoImputation-auto-complete.component';

// GismoUser ...
import { GismoUserService } from './entities/gismoUser/gismoUser.service';
import { GismoUserListComponent } from './entities/gismoUser/gismoUser-list.component';
import { GismoUserDetailComponent } from './entities/gismoUser/gismoUser-detail.component';
import { GismoUserLineComponent } from './entities/gismoUser/gismoUser-line.component';
import { GismoUserCompleteComponent } from './entities/gismoUser/gismoUser-auto-complete.component';

// JiraStates ...
import { JiraStatesService } from './entities/jiraStates/jiraStates.service';
import { JiraStatesListComponent } from './entities/jiraStates/jiraStates-list.component';
import { JiraStatesDetailComponent } from './entities/jiraStates/jiraStates-detail.component';
import { JiraStatesLineComponent } from './entities/jiraStates/jiraStates-line.component';
import { JiraStatesCompleteComponent } from './entities/jiraStates/jiraStates-auto-complete.component';

// JiraTask ...
import { JiraTaskService } from './entities/jiraTask/jiraTask.service';
import { JiraTaskListComponent } from './entities/jiraTask/jiraTask-list.component';
import { JiraTaskDetailComponent } from './entities/jiraTask/jiraTask-detail.component';
import { JiraTaskLineComponent } from './entities/jiraTask/jiraTask-line.component';
import { JiraTaskCompleteComponent } from './entities/jiraTask/jiraTask-auto-complete.component';

// JiraTaskType ...
import { JiraTaskTypeService } from './entities/jiraTaskType/jiraTaskType.service';
import { JiraTaskTypeListComponent } from './entities/jiraTaskType/jiraTaskType-list.component';
import { JiraTaskTypeDetailComponent } from './entities/jiraTaskType/jiraTaskType-detail.component';
import { JiraTaskTypeLineComponent } from './entities/jiraTaskType/jiraTaskType-line.component';
import { JiraTaskTypeCompleteComponent } from './entities/jiraTaskType/jiraTaskType-auto-complete.component';

// Profil ...
import { ProfilService } from './entities/profil/profil.service';
import { ProfilListComponent } from './entities/profil/profil-list.component';
import { ProfilDetailComponent } from './entities/profil/profil-detail.component';
import { ProfilLineComponent } from './entities/profil/profil-line.component';
import { ProfilCompleteComponent } from './entities/profil/profil-auto-complete.component';

// Project ...
import { ProjectService } from './entities/project/project.service';
import { ProjectListComponent } from './entities/project/project-list.component';
import { ProjectDetailComponent } from './entities/project/project-detail.component';
import { ProjectLineComponent } from './entities/project/project-line.component';
import { ProjectCompleteComponent } from './entities/project/project-auto-complete.component';

// ProjectGroup ...
import { ProjectGroupService } from './entities/projectGroup/projectGroup.service';
import { ProjectGroupListComponent } from './entities/projectGroup/projectGroup-list.component';
import { ProjectGroupDetailComponent } from './entities/projectGroup/projectGroup-detail.component';
import { ProjectGroupLineComponent } from './entities/projectGroup/projectGroup-line.component';
import { ProjectGroupCompleteComponent } from './entities/projectGroup/projectGroup-auto-complete.component';

// SubProject ...
import { SubProjectService } from './entities/subProject/subProject.service';
import { SubProjectListComponent } from './entities/subProject/subProject-list.component';
import { SubProjectDetailComponent } from './entities/subProject/subProject-detail.component';
import { SubProjectLineComponent } from './entities/subProject/subProject-line.component';
import { SubProjectCompleteComponent } from './entities/subProject/subProject-auto-complete.component';

// SubVersion ...
import { SubVersionService } from './entities/subVersion/subVersion.service';
import { SubVersionListComponent } from './entities/subVersion/subVersion-list.component';
import { SubVersionDetailComponent } from './entities/subVersion/subVersion-detail.component';
import { SubVersionLineComponent } from './entities/subVersion/subVersion-line.component';
import { SubVersionCompleteComponent } from './entities/subVersion/subVersion-auto-complete.component';

// Task ...
import { TaskService } from './entities/task/task.service';
import { TaskListComponent } from './entities/task/task-list.component';
import { TaskDetailComponent } from './entities/task/task-detail.component';
import { TaskLineComponent } from './entities/task/task-line.component';
import { TaskCompleteComponent } from './entities/task/task-auto-complete.component';

// TaskLink ...
import { TaskLinkService } from './entities/taskLink/taskLink.service';
import { TaskLinkListComponent } from './entities/taskLink/taskLink-list.component';
import { TaskLinkDetailComponent } from './entities/taskLink/taskLink-detail.component';
import { TaskLinkLineComponent } from './entities/taskLink/taskLink-line.component';
import { TaskLinkCompleteComponent } from './entities/taskLink/taskLink-auto-complete.component';

// TaskType ...
import { TaskTypeService } from './entities/taskType/taskType.service';
import { TaskTypeListComponent } from './entities/taskType/taskType-list.component';
import { TaskTypeDetailComponent } from './entities/taskType/taskType-detail.component';
import { TaskTypeLineComponent } from './entities/taskType/taskType-line.component';
import { TaskTypeCompleteComponent } from './entities/taskType/taskType-auto-complete.component';

// Version ...
import { VersionService } from './entities/version/version.service';
import { VersionListComponent } from './entities/version/version-list.component';
import { VersionDetailComponent } from './entities/version/version-detail.component';
import { VersionLineComponent } from './entities/version/version-line.component';
import { VersionCompleteComponent } from './entities/version/version-auto-complete.component';

// WeekNumber ...
import { WeekNumberService } from './entities/weekNumber/weekNumber.service';
import { WeekNumberListComponent } from './entities/weekNumber/weekNumber-list.component';
import { WeekNumberDetailComponent } from './entities/weekNumber/weekNumber-detail.component';
import { WeekNumberLineComponent } from './entities/weekNumber/weekNumber-line.component';
import { WeekNumberCompleteComponent } from './entities/weekNumber/weekNumber-auto-complete.component';



// Under Const ...
import { UnderConstComponent } from './under_const/under_const.component';


@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    EmailValidator,
    ConfirmDeleteDialogComponent
    ,
    UnderConstComponent
    ,
    CapitalImputationListComponent,
    CapitalImputationDetailComponent,
    CapitalImputationLineComponent,
    CapitalImputationCompleteComponent
    ,
    CapitalItemListComponent,
    CapitalItemDetailComponent,
    CapitalItemLineComponent,
    CapitalItemCompleteComponent
    ,
    CapitalOsListComponent,
    CapitalOsDetailComponent,
    CapitalOsLineComponent,
    CapitalOsCompleteComponent
    ,
    CapitalSubtypeListComponent,
    CapitalSubtypeDetailComponent,
    CapitalSubtypeLineComponent,
    CapitalSubtypeCompleteComponent
    ,
    GismoImputationListComponent,
    GismoImputationDetailComponent,
    GismoImputationLineComponent,
    GismoImputationCompleteComponent
    ,
    GismoUserListComponent,
    GismoUserDetailComponent,
    GismoUserLineComponent,
    GismoUserCompleteComponent
    ,
    JiraStatesListComponent,
    JiraStatesDetailComponent,
    JiraStatesLineComponent,
    JiraStatesCompleteComponent
    ,
    JiraTaskListComponent,
    JiraTaskDetailComponent,
    JiraTaskLineComponent,
    JiraTaskCompleteComponent
    ,
    JiraTaskTypeListComponent,
    JiraTaskTypeDetailComponent,
    JiraTaskTypeLineComponent,
    JiraTaskTypeCompleteComponent
    ,
    ProfilListComponent,
    ProfilDetailComponent,
    ProfilLineComponent,
    ProfilCompleteComponent
    ,
    ProjectListComponent,
    ProjectDetailComponent,
    ProjectLineComponent,
    ProjectCompleteComponent
    ,
    ProjectGroupListComponent,
    ProjectGroupDetailComponent,
    ProjectGroupLineComponent,
    ProjectGroupCompleteComponent
    ,
    SubProjectListComponent,
    SubProjectDetailComponent,
    SubProjectLineComponent,
    SubProjectCompleteComponent
    ,
    SubVersionListComponent,
    SubVersionDetailComponent,
    SubVersionLineComponent,
    SubVersionCompleteComponent
    ,
    TaskListComponent,
    TaskDetailComponent,
    TaskLineComponent,
    TaskCompleteComponent
    ,
    TaskLinkListComponent,
    TaskLinkDetailComponent,
    TaskLinkLineComponent,
    TaskLinkCompleteComponent
    ,
    TaskTypeListComponent,
    TaskTypeDetailComponent,
    TaskTypeLineComponent,
    TaskTypeCompleteComponent
    ,
    VersionListComponent,
    VersionDetailComponent,
    VersionLineComponent,
    VersionCompleteComponent
    ,
    WeekNumberListComponent,
    WeekNumberDetailComponent,
    WeekNumberLineComponent,
    WeekNumberCompleteComponent
    ],
    imports: [
// angular
        BrowserModule,
        BrowserAnimationsModule,
        FormsModule,
        HttpClientModule,

// angular material,
        MatDatepickerModule,
        MatNativeDateModule,
        MatDialogModule,
        MatCardModule,
        MatIconModule,
        MatSelectModule,
        MatTabsModule,
        MatInputModule,
        MatButtonModule,

// primeng
        ConfirmDialogModule,
        FileUploadModule,
        PanelModule,
        GrowlModule,
        MenubarModule,
        DialogModule,
        ButtonModule,
        AutoCompleteModule,
        DataTableModule,
        SharedModule,
        DropdownModule,
        PickListModule,
        CheckboxModule,
        TriStateCheckboxModule,
        InputTextModule,
        InputTextareaModule,
        CalendarModule,
        PasswordModule,
        TabViewModule,

// our application routes
        routing
    ],
    providers: [
// our application entity services
        CapitalImputationService,
        CapitalItemService,
        CapitalOsService,
        CapitalSubtypeService,
        GismoImputationService,
        GismoUserService,
        JiraStatesService,
        JiraTaskService,
        JiraTaskTypeService,
        ProfilService,
        ProjectService,
        ProjectGroupService,
        SubProjectService,
        SubVersionService,
        TaskService,
        TaskLinkService,
        TaskTypeService,
        VersionService,
        WeekNumberService,

// our application services
        AuthService,
        MessageService,

// primeng service
        ConfirmationService
    ],
    entryComponents: [ConfirmDeleteDialogComponent],
    bootstrap: [ AppComponent ]
})
export class AppModule {}
