//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/app.routes.ts.p.vm
//
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home.component';

import { CapitalImputationListComponent } from './entities/capitalImputation/capitalImputation-list.component';
import { CapitalImputationDetailComponent } from './entities/capitalImputation/capitalImputation-detail.component';

import { CapitalItemListComponent } from './entities/capitalItem/capitalItem-list.component';
import { CapitalItemDetailComponent } from './entities/capitalItem/capitalItem-detail.component';

import { CapitalOsListComponent } from './entities/capitalOs/capitalOs-list.component';
import { CapitalOsDetailComponent } from './entities/capitalOs/capitalOs-detail.component';

import { CapitalSubtypeListComponent } from './entities/capitalSubtype/capitalSubtype-list.component';
import { CapitalSubtypeDetailComponent } from './entities/capitalSubtype/capitalSubtype-detail.component';

import { GismoImputationListComponent } from './entities/gismoImputation/gismoImputation-list.component';
import { GismoImputationDetailComponent } from './entities/gismoImputation/gismoImputation-detail.component';

import { GismoUserListComponent } from './entities/gismoUser/gismoUser-list.component';
import { GismoUserDetailComponent } from './entities/gismoUser/gismoUser-detail.component';

import { JiraStatesListComponent } from './entities/jiraStates/jiraStates-list.component';
import { JiraStatesDetailComponent } from './entities/jiraStates/jiraStates-detail.component';

import { JiraTaskListComponent } from './entities/jiraTask/jiraTask-list.component';
import { JiraTaskDetailComponent } from './entities/jiraTask/jiraTask-detail.component';

import { JiraTaskTypeListComponent } from './entities/jiraTaskType/jiraTaskType-list.component';
import { JiraTaskTypeDetailComponent } from './entities/jiraTaskType/jiraTaskType-detail.component';

import { ProfilListComponent } from './entities/profil/profil-list.component';
import { ProfilDetailComponent } from './entities/profil/profil-detail.component';

import { ProjectListComponent } from './entities/project/project-list.component';
import { ProjectDetailComponent } from './entities/project/project-detail.component';

import { ProjectGroupListComponent } from './entities/projectGroup/projectGroup-list.component';
import { ProjectGroupDetailComponent } from './entities/projectGroup/projectGroup-detail.component';

import { SubProjectListComponent } from './entities/subProject/subProject-list.component';
import { SubProjectDetailComponent } from './entities/subProject/subProject-detail.component';

import { SubVersionListComponent } from './entities/subVersion/subVersion-list.component';
import { SubVersionDetailComponent } from './entities/subVersion/subVersion-detail.component';

import { TaskListComponent } from './entities/task/task-list.component';
import { TaskDetailComponent } from './entities/task/task-detail.component';

import { TaskLinkListComponent } from './entities/taskLink/taskLink-list.component';
import { TaskLinkDetailComponent } from './entities/taskLink/taskLink-detail.component';

import { TaskTypeListComponent } from './entities/taskType/taskType-list.component';
import { TaskTypeDetailComponent } from './entities/taskType/taskType-detail.component';

import { VersionListComponent } from './entities/version/version-list.component';
import { VersionDetailComponent } from './entities/version/version-detail.component';

import { WeekNumberListComponent } from './entities/weekNumber/weekNumber-list.component';
import { WeekNumberDetailComponent } from './entities/weekNumber/weekNumber-detail.component';

export const routes: Routes = [
    { path : '',  component: HomeComponent }
    ,
    {path: 'capitalImputation-list', component: CapitalImputationListComponent },
    {path: 'capitalImputation/:id', component: CapitalImputationDetailComponent }
    ,
    {path: 'capitalItem-list', component: CapitalItemListComponent },
    {path: 'capitalItem/:id', component: CapitalItemDetailComponent }
    ,
    {path: 'capitalOs-list', component: CapitalOsListComponent },
    {path: 'capitalOs/:id', component: CapitalOsDetailComponent }
    ,
    {path: 'capitalSubtype-list', component: CapitalSubtypeListComponent },
    {path: 'capitalSubtype/:id', component: CapitalSubtypeDetailComponent }
    ,
    {path: 'gismoImputation-list', component: GismoImputationListComponent },
    {path: 'gismoImputation/:id', component: GismoImputationDetailComponent }
    ,
    {path: 'gismoUser-list', component: GismoUserListComponent },
    {path: 'gismoUser/:id', component: GismoUserDetailComponent }
    ,
    {path: 'jiraStates-list', component: JiraStatesListComponent },
    {path: 'jiraStates/:id', component: JiraStatesDetailComponent }
    ,
    {path: 'jiraTask-list', component: JiraTaskListComponent },
    {path: 'jiraTask/:id', component: JiraTaskDetailComponent }
    ,
    {path: 'jiraTaskType-list', component: JiraTaskTypeListComponent },
    {path: 'jiraTaskType/:id', component: JiraTaskTypeDetailComponent }
    ,
    {path: 'profil-list', component: ProfilListComponent },
    {path: 'profil/:id', component: ProfilDetailComponent }
    ,
    {path: 'project-list', component: ProjectListComponent },
    {path: 'project/:id', component: ProjectDetailComponent }
    ,
    {path: 'projectGroup-list', component: ProjectGroupListComponent },
    {path: 'projectGroup/:id', component: ProjectGroupDetailComponent }
    ,
    {path: 'subProject-list', component: SubProjectListComponent },
    {path: 'subProject/:id', component: SubProjectDetailComponent }
    ,
    {path: 'subVersion-list', component: SubVersionListComponent },
    {path: 'subVersion/:id', component: SubVersionDetailComponent }
    ,
    {path: 'task-list', component: TaskListComponent },
    {path: 'task/:id', component: TaskDetailComponent }
    ,
    {path: 'taskLink-list', component: TaskLinkListComponent },
    {path: 'taskLink/:id', component: TaskLinkDetailComponent }
    ,
    {path: 'taskType-list', component: TaskTypeListComponent },
    {path: 'taskType/:id', component: TaskTypeDetailComponent }
    ,
    {path: 'version-list', component: VersionListComponent },
    {path: 'version/:id', component: VersionDetailComponent }
    ,
    {path: 'weekNumber-list', component: WeekNumberListComponent },
    {path: 'weekNumber/:id', component: WeekNumberDetailComponent }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
