//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { GismoImputation } from './gismoImputation';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class GismoImputationService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a GismoImputation by id.
     */
    getGismoImputation(id : any) : Observable<GismoImputation> {
        return this.http.get('/api/gismoImputations/' + id)
            .pipe(
                map(response => new GismoImputation(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed gismoImputation.
     */
    update(gismoImputation : GismoImputation) : Observable<GismoImputation> {
        let body = gismoImputation;

        return this.http.put('/api/gismoImputations/', body)
            .pipe(
                map(response => new GismoImputation(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of GismoImputation using the passed
     * gismoImputation as an example for the search by example facility.
     */
    getPage(gismoImputation : GismoImputation, event : LazyLoadEvent) : Observable<PageResponse<GismoImputation>> {
        let req = new PageRequestByExample(gismoImputation, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/gismoImputations/page', body)
            .pipe(
                map(pr =>  new PageResponse<GismoImputation>(pr.totalPages, pr.totalElements, GismoImputation.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by GismoImputationCompleteComponent.
     */
    complete(query : string) : Observable<GismoImputation[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/gismoImputations/complete', body)
            .pipe(
                map(response => GismoImputation.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an GismoImputation by id.
     */
    delete(id : any) {
        return this.http.delete('/api/gismoImputations/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
