//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class GismoImputation {
    // Raw attributes
    id : number;
    taskId : number;
    userId : number;
    imputdate : Date;
    imputtime : number;
    detail : string;
    weeknumberid : number;
    warning : string;
    error : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.taskId = json.taskId;
            this.userId = json.userId;
            if (json.imputdate != null) {
                this.imputdate = new Date(json.imputdate);
            }
            this.imputtime = json.imputtime;
            this.detail = json.detail;
            this.weeknumberid = json.weeknumberid;
            this.warning = json.warning;
            this.error = json.error;
        }
    }

    // Utils

    static toArray(jsons : any[]) : GismoImputation[] {
        let gismoImputations : GismoImputation[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                gismoImputations.push(new GismoImputation(json));
            }
        }
        return gismoImputations;
    }
}
