//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { GismoUser } from './gismoUser';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class GismoUserService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a GismoUser by id.
     */
    getGismoUser(id : any) : Observable<GismoUser> {
        return this.http.get('/api/gismoUsers/' + id)
            .pipe(
                map(response => new GismoUser(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed gismoUser.
     */
    update(gismoUser : GismoUser) : Observable<GismoUser> {
        let body = gismoUser;

        return this.http.put('/api/gismoUsers/', body)
            .pipe(
                map(response => new GismoUser(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of GismoUser using the passed
     * gismoUser as an example for the search by example facility.
     */
    getPage(gismoUser : GismoUser, event : LazyLoadEvent) : Observable<PageResponse<GismoUser>> {
        let req = new PageRequestByExample(gismoUser, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/gismoUsers/page', body)
            .pipe(
                map(pr =>  new PageResponse<GismoUser>(pr.totalPages, pr.totalElements, GismoUser.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by GismoUserCompleteComponent.
     */
    complete(query : string) : Observable<GismoUser[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/gismoUsers/complete', body)
            .pipe(
                map(response => GismoUser.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an GismoUser by id.
     */
    delete(id : any) {
        return this.http.delete('/api/gismoUsers/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
