/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.CapitalItem;
import com.apside.gismo.dto.CapitalItemDTO;
import com.apside.gismo.dto.CapitalItemDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.CapitalItemRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/capitalItems")
public class CapitalItemResource {

    private final Logger log = LoggerFactory.getLogger(CapitalItemResource.class);

    @Inject
    private CapitalItemRepository capitalItemRepository;
    @Inject
    private CapitalItemDTOService capitalItemDTOService;

    /**
     * Create a new CapitalItem.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<CapitalItemDTO> create(@RequestBody CapitalItemDTO capitalItemDTO) throws URISyntaxException {

        log.debug("Create CapitalItemDTO : {}", capitalItemDTO);

        if (capitalItemDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create CapitalItem with existing ID").body(null);
        }

        CapitalItemDTO result = capitalItemDTOService.save(capitalItemDTO);

        return ResponseEntity.created(new URI("/api/capitalItems/" + result.id)).body(result);
    }

    /**
    * Find by id CapitalItem.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<CapitalItemDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id CapitalItem : {}", id);

        return Optional.ofNullable(capitalItemDTOService.findOne(id)).map(capitalItemDTO -> new ResponseEntity<>(capitalItemDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update CapitalItem.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<CapitalItemDTO> update(@RequestBody CapitalItemDTO capitalItemDTO) throws URISyntaxException {

        log.debug("Update CapitalItemDTO : {}", capitalItemDTO);

        if (!capitalItemDTO.isIdSet()) {
            return create(capitalItemDTO);
        }

        CapitalItemDTO result = capitalItemDTOService.save(capitalItemDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of CapitalItem using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<CapitalItemDTO>> findAll(@RequestBody PageRequestByExample<CapitalItemDTO> prbe) throws URISyntaxException {
        PageResponse<CapitalItemDTO> pageResponse = capitalItemDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<CapitalItemDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<CapitalItemDTO> results = capitalItemDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id CapitalItem.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id CapitalItem : {}", id);

        try {
            capitalItemRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}