/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.CapitalImputation;
import com.apside.gismo.dto.CapitalImputationDTO;
import com.apside.gismo.dto.CapitalImputationDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.CapitalImputationRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/capitalImputations")
public class CapitalImputationResource {

    private final Logger log = LoggerFactory.getLogger(CapitalImputationResource.class);

    @Inject
    private CapitalImputationRepository capitalImputationRepository;
    @Inject
    private CapitalImputationDTOService capitalImputationDTOService;

    /**
     * Create a new CapitalImputation.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<CapitalImputationDTO> create(@RequestBody CapitalImputationDTO capitalImputationDTO) throws URISyntaxException {

        log.debug("Create CapitalImputationDTO : {}", capitalImputationDTO);

        if (capitalImputationDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create CapitalImputation with existing ID").body(null);
        }

        CapitalImputationDTO result = capitalImputationDTOService.save(capitalImputationDTO);

        return ResponseEntity.created(new URI("/api/capitalImputations/" + result.id)).body(result);
    }

    /**
    * Find by id CapitalImputation.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<CapitalImputationDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id CapitalImputation : {}", id);

        return Optional.ofNullable(capitalImputationDTOService.findOne(id))
                .map(capitalImputationDTO -> new ResponseEntity<>(capitalImputationDTO, HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update CapitalImputation.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<CapitalImputationDTO> update(@RequestBody CapitalImputationDTO capitalImputationDTO) throws URISyntaxException {

        log.debug("Update CapitalImputationDTO : {}", capitalImputationDTO);

        if (!capitalImputationDTO.isIdSet()) {
            return create(capitalImputationDTO);
        }

        CapitalImputationDTO result = capitalImputationDTOService.save(capitalImputationDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of CapitalImputation using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<CapitalImputationDTO>> findAll(@RequestBody PageRequestByExample<CapitalImputationDTO> prbe) throws URISyntaxException {
        PageResponse<CapitalImputationDTO> pageResponse = capitalImputationDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<CapitalImputationDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<CapitalImputationDTO> results = capitalImputationDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id CapitalImputation.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id CapitalImputation : {}", id);

        try {
            capitalImputationRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}