/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.GismoImputation;
import com.apside.gismo.dto.GismoImputationDTO;
import com.apside.gismo.dto.GismoImputationDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.GismoImputationRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/gismoImputations")
public class GismoImputationResource {

    private final Logger log = LoggerFactory.getLogger(GismoImputationResource.class);

    @Inject
    private GismoImputationRepository gismoImputationRepository;
    @Inject
    private GismoImputationDTOService gismoImputationDTOService;

    /**
     * Create a new GismoImputation.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GismoImputationDTO> create(@RequestBody GismoImputationDTO gismoImputationDTO) throws URISyntaxException {

        log.debug("Create GismoImputationDTO : {}", gismoImputationDTO);

        if (gismoImputationDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create GismoImputation with existing ID").body(null);
        }

        GismoImputationDTO result = gismoImputationDTOService.save(gismoImputationDTO);

        return ResponseEntity.created(new URI("/api/gismoImputations/" + result.id)).body(result);
    }

    /**
    * Find by id GismoImputation.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GismoImputationDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id GismoImputation : {}", id);

        return Optional.ofNullable(gismoImputationDTOService.findOne(id)).map(gismoImputationDTO -> new ResponseEntity<>(gismoImputationDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update GismoImputation.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GismoImputationDTO> update(@RequestBody GismoImputationDTO gismoImputationDTO) throws URISyntaxException {

        log.debug("Update GismoImputationDTO : {}", gismoImputationDTO);

        if (!gismoImputationDTO.isIdSet()) {
            return create(gismoImputationDTO);
        }

        GismoImputationDTO result = gismoImputationDTOService.save(gismoImputationDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of GismoImputation using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<GismoImputationDTO>> findAll(@RequestBody PageRequestByExample<GismoImputationDTO> prbe) throws URISyntaxException {
        PageResponse<GismoImputationDTO> pageResponse = gismoImputationDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<GismoImputationDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<GismoImputationDTO> results = gismoImputationDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id GismoImputation.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id GismoImputation : {}", id);

        try {
            gismoImputationRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}