/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.JiraStates;
import com.apside.gismo.dto.JiraStatesDTO;
import com.apside.gismo.dto.JiraStatesDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.JiraStatesRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/jiraStatess")
public class JiraStatesResource {

    private final Logger log = LoggerFactory.getLogger(JiraStatesResource.class);

    @Inject
    private JiraStatesRepository jiraStatesRepository;
    @Inject
    private JiraStatesDTOService jiraStatesDTOService;

    /**
     * Create a new JiraStates.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<JiraStatesDTO> create(@RequestBody JiraStatesDTO jiraStatesDTO) throws URISyntaxException {

        log.debug("Create JiraStatesDTO : {}", jiraStatesDTO);

        if (jiraStatesDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create JiraStates with existing ID").body(null);
        }

        JiraStatesDTO result = jiraStatesDTOService.save(jiraStatesDTO);

        return ResponseEntity.created(new URI("/api/jiraStatess/" + result.id)).body(result);
    }

    /**
    * Find by id JiraStates.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<JiraStatesDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id JiraStates : {}", id);

        return Optional.ofNullable(jiraStatesDTOService.findOne(id)).map(jiraStatesDTO -> new ResponseEntity<>(jiraStatesDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update JiraStates.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<JiraStatesDTO> update(@RequestBody JiraStatesDTO jiraStatesDTO) throws URISyntaxException {

        log.debug("Update JiraStatesDTO : {}", jiraStatesDTO);

        if (!jiraStatesDTO.isIdSet()) {
            return create(jiraStatesDTO);
        }

        JiraStatesDTO result = jiraStatesDTOService.save(jiraStatesDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of JiraStates using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<JiraStatesDTO>> findAll(@RequestBody PageRequestByExample<JiraStatesDTO> prbe) throws URISyntaxException {
        PageResponse<JiraStatesDTO> pageResponse = jiraStatesDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<JiraStatesDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<JiraStatesDTO> results = jiraStatesDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id JiraStates.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id JiraStates : {}", id);

        try {
            jiraStatesRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}