/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.JiraTaskType;
import com.apside.gismo.dto.JiraTaskTypeDTO;
import com.apside.gismo.dto.JiraTaskTypeDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.JiraTaskTypeRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/jiraTaskTypes")
public class JiraTaskTypeResource {

    private final Logger log = LoggerFactory.getLogger(JiraTaskTypeResource.class);

    @Inject
    private JiraTaskTypeRepository jiraTaskTypeRepository;
    @Inject
    private JiraTaskTypeDTOService jiraTaskTypeDTOService;

    /**
     * Create a new JiraTaskType.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<JiraTaskTypeDTO> create(@RequestBody JiraTaskTypeDTO jiraTaskTypeDTO) throws URISyntaxException {

        log.debug("Create JiraTaskTypeDTO : {}", jiraTaskTypeDTO);

        if (jiraTaskTypeDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create JiraTaskType with existing ID").body(null);
        }

        JiraTaskTypeDTO result = jiraTaskTypeDTOService.save(jiraTaskTypeDTO);

        return ResponseEntity.created(new URI("/api/jiraTaskTypes/" + result.id)).body(result);
    }

    /**
    * Find by id JiraTaskType.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<JiraTaskTypeDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id JiraTaskType : {}", id);

        return Optional.ofNullable(jiraTaskTypeDTOService.findOne(id)).map(jiraTaskTypeDTO -> new ResponseEntity<>(jiraTaskTypeDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update JiraTaskType.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<JiraTaskTypeDTO> update(@RequestBody JiraTaskTypeDTO jiraTaskTypeDTO) throws URISyntaxException {

        log.debug("Update JiraTaskTypeDTO : {}", jiraTaskTypeDTO);

        if (!jiraTaskTypeDTO.isIdSet()) {
            return create(jiraTaskTypeDTO);
        }

        JiraTaskTypeDTO result = jiraTaskTypeDTOService.save(jiraTaskTypeDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of JiraTaskType using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<JiraTaskTypeDTO>> findAll(@RequestBody PageRequestByExample<JiraTaskTypeDTO> prbe) throws URISyntaxException {
        PageResponse<JiraTaskTypeDTO> pageResponse = jiraTaskTypeDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<JiraTaskTypeDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<JiraTaskTypeDTO> results = jiraTaskTypeDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id JiraTaskType.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id JiraTaskType : {}", id);

        try {
            jiraTaskTypeRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}