/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.Profil;
import com.apside.gismo.dto.ProfilDTO;
import com.apside.gismo.dto.ProfilDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.ProfilRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/profils")
public class ProfilResource {

    private final Logger log = LoggerFactory.getLogger(ProfilResource.class);

    @Inject
    private ProfilRepository profilRepository;
    @Inject
    private ProfilDTOService profilDTOService;

    /**
     * Create a new Profil.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ProfilDTO> create(@RequestBody ProfilDTO profilDTO) throws URISyntaxException {

        log.debug("Create ProfilDTO : {}", profilDTO);

        if (profilDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Profil with existing ID").body(null);
        }

        ProfilDTO result = profilDTOService.save(profilDTO);

        return ResponseEntity.created(new URI("/api/profils/" + result.id)).body(result);
    }

    /**
    * Find by id Profil.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ProfilDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Profil : {}", id);

        return Optional.ofNullable(profilDTOService.findOne(id)).map(profilDTO -> new ResponseEntity<>(profilDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Profil.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ProfilDTO> update(@RequestBody ProfilDTO profilDTO) throws URISyntaxException {

        log.debug("Update ProfilDTO : {}", profilDTO);

        if (!profilDTO.isIdSet()) {
            return create(profilDTO);
        }

        ProfilDTO result = profilDTOService.save(profilDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Profil using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<ProfilDTO>> findAll(@RequestBody PageRequestByExample<ProfilDTO> prbe) throws URISyntaxException {
        PageResponse<ProfilDTO> pageResponse = profilDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ProfilDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<ProfilDTO> results = profilDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Profil.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Profil : {}", id);

        try {
            profilRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}