/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.SubVersion;
import com.apside.gismo.dto.SubVersionDTO;
import com.apside.gismo.dto.SubVersionDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.SubVersionRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/subVersions")
public class SubVersionResource {

    private final Logger log = LoggerFactory.getLogger(SubVersionResource.class);

    @Inject
    private SubVersionRepository subVersionRepository;
    @Inject
    private SubVersionDTOService subVersionDTOService;

    /**
     * Create a new SubVersion.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SubVersionDTO> create(@RequestBody SubVersionDTO subVersionDTO) throws URISyntaxException {

        log.debug("Create SubVersionDTO : {}", subVersionDTO);

        if (subVersionDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create SubVersion with existing ID").body(null);
        }

        SubVersionDTO result = subVersionDTOService.save(subVersionDTO);

        return ResponseEntity.created(new URI("/api/subVersions/" + result.id)).body(result);
    }

    /**
    * Find by id SubVersion.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SubVersionDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id SubVersion : {}", id);

        return Optional.ofNullable(subVersionDTOService.findOne(id)).map(subVersionDTO -> new ResponseEntity<>(subVersionDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update SubVersion.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<SubVersionDTO> update(@RequestBody SubVersionDTO subVersionDTO) throws URISyntaxException {

        log.debug("Update SubVersionDTO : {}", subVersionDTO);

        if (!subVersionDTO.isIdSet()) {
            return create(subVersionDTO);
        }

        SubVersionDTO result = subVersionDTOService.save(subVersionDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of SubVersion using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<SubVersionDTO>> findAll(@RequestBody PageRequestByExample<SubVersionDTO> prbe) throws URISyntaxException {
        PageResponse<SubVersionDTO> pageResponse = subVersionDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SubVersionDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<SubVersionDTO> results = subVersionDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id SubVersion.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id SubVersion : {}", id);

        try {
            subVersionRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}