/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.apside.gismo.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.apside.gismo.domain.Version;
import com.apside.gismo.dto.VersionDTO;
import com.apside.gismo.dto.VersionDTOService;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.VersionRepository;
import com.apside.gismo.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/versions")
public class VersionResource {

    private final Logger log = LoggerFactory.getLogger(VersionResource.class);

    @Inject
    private VersionRepository versionRepository;
    @Inject
    private VersionDTOService versionDTOService;

    /**
     * Create a new Version.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<VersionDTO> create(@RequestBody VersionDTO versionDTO) throws URISyntaxException {

        log.debug("Create VersionDTO : {}", versionDTO);

        if (versionDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Version with existing ID").body(null);
        }

        VersionDTO result = versionDTOService.save(versionDTO);

        return ResponseEntity.created(new URI("/api/versions/" + result.id)).body(result);
    }

    /**
    * Find by id Version.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<VersionDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Version : {}", id);

        return Optional.ofNullable(versionDTOService.findOne(id)).map(versionDTO -> new ResponseEntity<>(versionDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Version.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<VersionDTO> update(@RequestBody VersionDTO versionDTO) throws URISyntaxException {

        log.debug("Update VersionDTO : {}", versionDTO);

        if (!versionDTO.isIdSet()) {
            return create(versionDTO);
        }

        VersionDTO result = versionDTOService.save(versionDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Version using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<VersionDTO>> findAll(@RequestBody PageRequestByExample<VersionDTO> prbe) throws URISyntaxException {
        PageResponse<VersionDTO> pageResponse = versionDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<VersionDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<VersionDTO> results = versionDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Version.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Version : {}", id);

        try {
            versionRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}