//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Task {
    // Raw attributes
    id : number;
    externalId : string;
    name : string;
    taskTypeId : number;
    level : string;
    projectId : number;
    versionId : number;
    subProjectId : number;
    subVersionId : number;
    state : string;
    consumedtime : number;
    previewtime : number;
    remaintime : number;
    isguarantee : number;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.externalId = json.externalId;
            this.name = json.name;
            this.taskTypeId = json.taskTypeId;
            this.level = json.level;
            this.projectId = json.projectId;
            this.versionId = json.versionId;
            this.subProjectId = json.subProjectId;
            this.subVersionId = json.subVersionId;
            this.state = json.state;
            this.consumedtime = json.consumedtime;
            this.previewtime = json.previewtime;
            this.remaintime = json.remaintime;
            this.isguarantee = json.isguarantee;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Task[] {
        let tasks : Task[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                tasks.push(new Task(json));
            }
        }
        return tasks;
    }
}
