//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {TaskType} from './taskType';
import {TaskTypeService} from './taskType.service';

@Component({
    moduleId: module.id,
	templateUrl: 'taskType-detail.component.html',
	selector: 'taskType-detail',
})
export class TaskTypeDetailComponent implements OnInit, OnDestroy {
    taskType : TaskType;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<TaskType>();
    @Output() onCancelClicked = new EventEmitter();
    typeOptions: SelectItem[];

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private taskTypeService: TaskTypeService) {
        this.typeOptions = [];
        this.typeOptions.push({"label": "Unité d'oeuvre", 'value': "UO"});
        this.typeOptions.push({"label": "Support/AT", 'value': "SUPPORT"});
        this.typeOptions.push({"label": "Forfait", 'value': "FORFAIT"});
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for taskType-detail ' + id);

            if (id === 'new') {
                this.taskType = new TaskType();
            } else {
                this.taskTypeService.getTaskType(id)
                    .subscribe(taskType => {
                            this.taskType = taskType;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.taskTypeService.update(this.taskType).
            subscribe(
                taskType => {
                    this.taskType = taskType;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.taskType);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
