//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Profil {
    // Raw attributes
    id : number;
    type : string;
    userId : number;
    projectGroupId : number;
    projectId : number;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.type = json.type;
            this.userId = json.userId;
            this.projectGroupId = json.projectGroupId;
            this.projectId = json.projectId;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Profil[] {
        let profils : Profil[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                profils.push(new Profil(json));
            }
        }
        return profils;
    }
}
