//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { Profil } from './profil';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class ProfilService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a Profil by id.
     */
    getProfil(id : any) : Observable<Profil> {
        return this.http.get('/api/profils/' + id)
            .pipe(
                map(response => new Profil(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed profil.
     */
    update(profil : Profil) : Observable<Profil> {
        let body = profil;

        return this.http.put('/api/profils/', body)
            .pipe(
                map(response => new Profil(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of Profil using the passed
     * profil as an example for the search by example facility.
     */
    getPage(profil : Profil, event : LazyLoadEvent) : Observable<PageResponse<Profil>> {
        let req = new PageRequestByExample(profil, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/profils/page', body)
            .pipe(
                map(pr =>  new PageResponse<Profil>(pr.totalPages, pr.totalElements, Profil.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by ProfilCompleteComponent.
     */
    complete(query : string) : Observable<Profil[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/profils/complete', body)
            .pipe(
                map(response => Profil.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an Profil by id.
     */
    delete(id : any) {
        return this.http.delete('/api/profils/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
