/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(CapitalSubtype.class)
public abstract class CapitalSubtype_ {

    // Raw attributes
    public static volatile SingularAttribute<CapitalSubtype, Integer> id;
    public static volatile SingularAttribute<CapitalSubtype, String> capitalsubtype2;
    public static volatile SingularAttribute<CapitalSubtype, String> capitalitem;
    public static volatile SingularAttribute<CapitalSubtype, Integer> projectId;
    public static volatile SingularAttribute<CapitalSubtype, Integer> tasktypeid;
}