/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(CapitalOs.class)
public abstract class CapitalOs_ {

    // Raw attributes
    public static volatile SingularAttribute<CapitalOs, Integer> id;
    public static volatile SingularAttribute<CapitalOs, String> ident;
    public static volatile SingularAttribute<CapitalOs, String> name;
    public static volatile SingularAttribute<CapitalOs, Integer> projectId;
    public static volatile SingularAttribute<CapitalOs, Integer> versionId;
}