/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.apside.gismo.domain;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "CAPITAL_IMPUTATION")
public class CapitalImputation implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(CapitalImputation.class.getName());

    // Raw attributes
    private Integer id;
    private String dateyear;
    private String dateweek;
    private String dateday;
    private String username;
    private String osname;
    private Integer timeconsume;
    private String subtype;
    private String osident;
    private String item;
    private String complement;
    private String comment;
    private String phase;
    private Integer weekid;
    private Integer userId;
    private Integer capitalosid;
    private Integer projectId;
    private Integer subProjectId;
    private Integer tasktypeid;
    private Integer taskid;
    private String warning;
    private String error;

    @Override
    public String entityClassName() {
        return CapitalImputation.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "ID", precision = 10)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public CapitalImputation id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [dateyear] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "DATEYEAR", nullable = false)
    public String getDateyear() {
        return dateyear;
    }

    public void setDateyear(String dateyear) {
        this.dateyear = dateyear;
    }

    public CapitalImputation dateyear(String dateyear) {
        setDateyear(dateyear);
        return this;
    }
    // -- [dateweek] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "DATEWEEK", nullable = false)
    public String getDateweek() {
        return dateweek;
    }

    public void setDateweek(String dateweek) {
        this.dateweek = dateweek;
    }

    public CapitalImputation dateweek(String dateweek) {
        setDateweek(dateweek);
        return this;
    }
    // -- [dateday] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "DATEDAY", nullable = false)
    public String getDateday() {
        return dateday;
    }

    public void setDateday(String dateday) {
        this.dateday = dateday;
    }

    public CapitalImputation dateday(String dateday) {
        setDateday(dateday);
        return this;
    }
    // -- [username] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "USERNAME", nullable = false)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public CapitalImputation username(String username) {
        setUsername(username);
        return this;
    }
    // -- [osname] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "OSNAME", nullable = false)
    public String getOsname() {
        return osname;
    }

    public void setOsname(String osname) {
        this.osname = osname;
    }

    public CapitalImputation osname(String osname) {
        setOsname(osname);
        return this;
    }
    // -- [timeconsume] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "TIMECONSUME", nullable = false, precision = 10)
    public Integer getTimeconsume() {
        return timeconsume;
    }

    public void setTimeconsume(Integer timeconsume) {
        this.timeconsume = timeconsume;
    }

    public CapitalImputation timeconsume(Integer timeconsume) {
        setTimeconsume(timeconsume);
        return this;
    }
    // -- [subtype] ------------------------

    @Size(max = 255)
    @Column(name = "\"SUBTYPE\"")
    public String getSubtype() {
        return subtype;
    }

    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }

    public CapitalImputation subtype(String subtype) {
        setSubtype(subtype);
        return this;
    }
    // -- [osident] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "OSIDENT", nullable = false)
    public String getOsident() {
        return osident;
    }

    public void setOsident(String osident) {
        this.osident = osident;
    }

    public CapitalImputation osident(String osident) {
        setOsident(osident);
        return this;
    }
    // -- [item] ------------------------

    @Size(max = 255)
    @Column(name = "ITEM")
    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public CapitalImputation item(String item) {
        setItem(item);
        return this;
    }
    // -- [complement] ------------------------

    @Size(max = 255)
    @Column(name = "COMPLEMENT")
    public String getComplement() {
        return complement;
    }

    public void setComplement(String complement) {
        this.complement = complement;
    }

    public CapitalImputation complement(String complement) {
        setComplement(complement);
        return this;
    }
    // -- [comment] ------------------------

    @Size(max = 255)
    @Column(name = "\"COMMENT\"")
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public CapitalImputation comment(String comment) {
        setComment(comment);
        return this;
    }
    // -- [phase] ------------------------

    @Size(max = 255)
    @Column(name = "PHASE")
    public String getPhase() {
        return phase;
    }

    public void setPhase(String phase) {
        this.phase = phase;
    }

    public CapitalImputation phase(String phase) {
        setPhase(phase);
        return this;
    }
    // -- [weekid] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "WEEKID", precision = 10)
    public Integer getWeekid() {
        return weekid;
    }

    public void setWeekid(Integer weekid) {
        this.weekid = weekid;
    }

    public CapitalImputation weekid(Integer weekid) {
        setWeekid(weekid);
        return this;
    }
    // -- [userId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "USER_ID", precision = 10)
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public CapitalImputation userId(Integer userId) {
        setUserId(userId);
        return this;
    }
    // -- [capitalosid] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "CAPITALOSID", precision = 10)
    public Integer getCapitalosid() {
        return capitalosid;
    }

    public void setCapitalosid(Integer capitalosid) {
        this.capitalosid = capitalosid;
    }

    public CapitalImputation capitalosid(Integer capitalosid) {
        setCapitalosid(capitalosid);
        return this;
    }
    // -- [projectId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "PROJECT_ID", nullable = false, precision = 10)
    public Integer getProjectId() {
        return projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public CapitalImputation projectId(Integer projectId) {
        setProjectId(projectId);
        return this;
    }
    // -- [subProjectId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "SUB_PROJECT_ID", precision = 10)
    public Integer getSubProjectId() {
        return subProjectId;
    }

    public void setSubProjectId(Integer subProjectId) {
        this.subProjectId = subProjectId;
    }

    public CapitalImputation subProjectId(Integer subProjectId) {
        setSubProjectId(subProjectId);
        return this;
    }
    // -- [tasktypeid] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "TASKTYPEID", precision = 10)
    public Integer getTasktypeid() {
        return tasktypeid;
    }

    public void setTasktypeid(Integer tasktypeid) {
        this.tasktypeid = tasktypeid;
    }

    public CapitalImputation tasktypeid(Integer tasktypeid) {
        setTasktypeid(tasktypeid);
        return this;
    }
    // -- [taskid] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "TASKID", precision = 10)
    public Integer getTaskid() {
        return taskid;
    }

    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    public CapitalImputation taskid(Integer taskid) {
        setTaskid(taskid);
        return this;
    }
    // -- [warning] ------------------------

    @Size(max = 255)
    @Column(name = "WARNING")
    public String getWarning() {
        return warning;
    }

    public void setWarning(String warning) {
        this.warning = warning;
    }

    public CapitalImputation warning(String warning) {
        setWarning(warning);
        return this;
    }
    // -- [error] ------------------------

    @Size(max = 255)
    @Column(name = "ERROR")
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public CapitalImputation error(String error) {
        setError(error);
        return this;
    }

    /**
     * Apply the default values.
     */
    public CapitalImputation withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof CapitalImputation && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this CapitalImputation instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("dateyear", getDateyear()) //
                .add("dateweek", getDateweek()) //
                .add("dateday", getDateday()) //
                .add("username", getUsername()) //
                .add("osname", getOsname()) //
                .add("timeconsume", getTimeconsume()) //
                .add("subtype", getSubtype()) //
                .add("osident", getOsident()) //
                .add("item", getItem()) //
                .add("complement", getComplement()) //
                .add("comment", getComment()) //
                .add("phase", getPhase()) //
                .add("weekid", getWeekid()) //
                .add("userId", getUserId()) //
                .add("capitalosid", getCapitalosid()) //
                .add("projectId", getProjectId()) //
                .add("subProjectId", getSubProjectId()) //
                .add("tasktypeid", getTasktypeid()) //
                .add("taskid", getTaskid()) //
                .add("warning", getWarning()) //
                .add("error", getError()) //
                .toString();
    }
}