/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.apside.gismo.domain;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "GISMO_USER")
public class GismoUser implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(GismoUser.class.getName());

    // Raw attributes
    private Integer id;
    private String name;
    private String trigramme;
    private String capitalName;
    private String jiraName;

    @Override
    public String entityClassName() {
        return GismoUser.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "ID", precision = 10)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public GismoUser id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [name] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "NAME", nullable = false)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public GismoUser name(String name) {
        setName(name);
        return this;
    }
    // -- [trigramme] ------------------------

    @NotEmpty
    @Size(max = 3)
    @Column(name = "TRIGRAMME", nullable = false, length = 3)
    public String getTrigramme() {
        return trigramme;
    }

    public void setTrigramme(String trigramme) {
        this.trigramme = trigramme;
    }

    public GismoUser trigramme(String trigramme) {
        setTrigramme(trigramme);
        return this;
    }
    // -- [capitalName] ------------------------

    @Size(max = 255)
    @Column(name = "CAPITAL_NAME")
    public String getCapitalName() {
        return capitalName;
    }

    public void setCapitalName(String capitalName) {
        this.capitalName = capitalName;
    }

    public GismoUser capitalName(String capitalName) {
        setCapitalName(capitalName);
        return this;
    }
    // -- [jiraName] ------------------------

    @Size(max = 255)
    @Column(name = "JIRA_NAME")
    public String getJiraName() {
        return jiraName;
    }

    public void setJiraName(String jiraName) {
        this.jiraName = jiraName;
    }

    public GismoUser jiraName(String jiraName) {
        setJiraName(jiraName);
        return this;
    }

    /**
     * Apply the default values.
     */
    public GismoUser withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof GismoUser && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this GismoUser instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("name", getName()) //
                .add("trigramme", getTrigramme()) //
                .add("capitalName", getCapitalName()) //
                .add("jiraName", getJiraName()) //
                .toString();
    }
}