/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import java.time.LocalDate;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(GismoImputation.class)
public abstract class GismoImputation_ {

    // Raw attributes
    public static volatile SingularAttribute<GismoImputation, Integer> id;
    public static volatile SingularAttribute<GismoImputation, Integer> taskId;
    public static volatile SingularAttribute<GismoImputation, Integer> userId;
    public static volatile SingularAttribute<GismoImputation, LocalDate> imputdate;
    public static volatile SingularAttribute<GismoImputation, Integer> imputtime;
    public static volatile SingularAttribute<GismoImputation, String> detail;
    public static volatile SingularAttribute<GismoImputation, Integer> weeknumberid;
    public static volatile SingularAttribute<GismoImputation, String> warning;
    public static volatile SingularAttribute<GismoImputation, String> error;
}