/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(JiraTaskType.class)
public abstract class JiraTaskType_ {

    // Raw attributes
    public static volatile SingularAttribute<JiraTaskType, Integer> id;
    public static volatile SingularAttribute<JiraTaskType, String> issuetype;
    public static volatile SingularAttribute<JiraTaskType, String> myComponent;
    public static volatile SingularAttribute<JiraTaskType, Integer> taskTypeId;
}