/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.apside.gismo.domain;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "JIRA_TASK_TYPE")
public class JiraTaskType implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(JiraTaskType.class.getName());

    // Raw attributes
    private Integer id;
    private String issuetype;
    private String myComponent;
    private Integer taskTypeId;

    @Override
    public String entityClassName() {
        return JiraTaskType.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "ID", precision = 10)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public JiraTaskType id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [issuetype] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "ISSUETYPE", nullable = false)
    public String getIssuetype() {
        return issuetype;
    }

    public void setIssuetype(String issuetype) {
        this.issuetype = issuetype;
    }

    public JiraTaskType issuetype(String issuetype) {
        setIssuetype(issuetype);
        return this;
    }
    // -- [myComponent] ------------------------

    @Size(max = 255)
    @Column(name = "COMPONENT")
    public String getMyComponent() {
        return myComponent;
    }

    public void setMyComponent(String myComponent) {
        this.myComponent = myComponent;
    }

    public JiraTaskType myComponent(String myComponent) {
        setMyComponent(myComponent);
        return this;
    }
    // -- [taskTypeId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "TASK_TYPE_ID", precision = 10)
    public Integer getTaskTypeId() {
        return taskTypeId;
    }

    public void setTaskTypeId(Integer taskTypeId) {
        this.taskTypeId = taskTypeId;
    }

    public JiraTaskType taskTypeId(Integer taskTypeId) {
        setTaskTypeId(taskTypeId);
        return this;
    }

    /**
     * Apply the default values.
     */
    public JiraTaskType withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof JiraTaskType && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this JiraTaskType instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("issuetype", getIssuetype()) //
                .add("myComponent", getMyComponent()) //
                .add("taskTypeId", getTaskTypeId()) //
                .toString();
    }
}