/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(JiraTask.class)
public abstract class JiraTask_ {

    // Raw attributes
    public static volatile SingularAttribute<JiraTask, Integer> id;
    public static volatile SingularAttribute<JiraTask, String> projectname;
    public static volatile SingularAttribute<JiraTask, String> ident;
    public static volatile SingularAttribute<JiraTask, String> issuetype;
    public static volatile SingularAttribute<JiraTask, String> summary;
    public static volatile SingularAttribute<JiraTask, String> severity;
    public static volatile SingularAttribute<JiraTask, String> status;
    public static volatile SingularAttribute<JiraTask, String> priority;
    public static volatile SingularAttribute<JiraTask, String> assignee;
    public static volatile SingularAttribute<JiraTask, String> reporter;
    public static volatile SingularAttribute<JiraTask, String> components;
    public static volatile SingularAttribute<JiraTask, String> linkedissue;
    public static volatile SingularAttribute<JiraTask, String> affversion;
    public static volatile SingularAttribute<JiraTask, String> targetversion;
    public static volatile SingularAttribute<JiraTask, String> deliveryversion;
    public static volatile SingularAttribute<JiraTask, Integer> projectId;
    public static volatile SingularAttribute<JiraTask, Integer> versionId;
    public static volatile SingularAttribute<JiraTask, Integer> subProjectId;
    public static volatile SingularAttribute<JiraTask, Integer> subVersionId;
    public static volatile SingularAttribute<JiraTask, Integer> taskTypeId;
    public static volatile SingularAttribute<JiraTask, Integer> taskId;
    public static volatile SingularAttribute<JiraTask, String> state;
    public static volatile SingularAttribute<JiraTask, String> warning;
    public static volatile SingularAttribute<JiraTask, String> error;
}