/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.apside.gismo.domain;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "JIRA_TASK")
public class JiraTask implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(JiraTask.class.getName());

    // Raw attributes
    private Integer id;
    private String projectname;
    private String ident;
    private String issuetype;
    private String summary;
    private String severity;
    private String status;
    private String priority;
    private String assignee;
    private String reporter;
    private String components;
    private String linkedissue;
    private String affversion;
    private String targetversion;
    private String deliveryversion;
    private Integer projectId;
    private Integer versionId;
    private Integer subProjectId;
    private Integer subVersionId;
    private Integer taskTypeId;
    private Integer taskId;
    private String state;
    private String warning;
    private String error;

    @Override
    public String entityClassName() {
        return JiraTask.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "ID", precision = 10)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public JiraTask id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [projectname] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "PROJECTNAME", nullable = false)
    public String getProjectname() {
        return projectname;
    }

    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    public JiraTask projectname(String projectname) {
        setProjectname(projectname);
        return this;
    }
    // -- [ident] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "IDENT", nullable = false)
    public String getIdent() {
        return ident;
    }

    public void setIdent(String ident) {
        this.ident = ident;
    }

    public JiraTask ident(String ident) {
        setIdent(ident);
        return this;
    }
    // -- [issuetype] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "ISSUETYPE", nullable = false)
    public String getIssuetype() {
        return issuetype;
    }

    public void setIssuetype(String issuetype) {
        this.issuetype = issuetype;
    }

    public JiraTask issuetype(String issuetype) {
        setIssuetype(issuetype);
        return this;
    }
    // -- [summary] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "SUMMARY", nullable = false)
    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public JiraTask summary(String summary) {
        setSummary(summary);
        return this;
    }
    // -- [severity] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "SEVERITY", nullable = false)
    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public JiraTask severity(String severity) {
        setSeverity(severity);
        return this;
    }
    // -- [status] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "STATUS", nullable = false)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public JiraTask status(String status) {
        setStatus(status);
        return this;
    }
    // -- [priority] ------------------------

    @Size(max = 255)
    @Column(name = "PRIORITY")
    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public JiraTask priority(String priority) {
        setPriority(priority);
        return this;
    }
    // -- [assignee] ------------------------

    @Size(max = 255)
    @Column(name = "ASSIGNEE")
    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    public JiraTask assignee(String assignee) {
        setAssignee(assignee);
        return this;
    }
    // -- [reporter] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "REPORTER", nullable = false)
    public String getReporter() {
        return reporter;
    }

    public void setReporter(String reporter) {
        this.reporter = reporter;
    }

    public JiraTask reporter(String reporter) {
        setReporter(reporter);
        return this;
    }
    // -- [components] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "COMPONENTS", nullable = false)
    public String getComponents() {
        return components;
    }

    public void setComponents(String components) {
        this.components = components;
    }

    public JiraTask components(String components) {
        setComponents(components);
        return this;
    }
    // -- [linkedissue] ------------------------

    @Size(max = 255)
    @Column(name = "LINKEDISSUE")
    public String getLinkedissue() {
        return linkedissue;
    }

    public void setLinkedissue(String linkedissue) {
        this.linkedissue = linkedissue;
    }

    public JiraTask linkedissue(String linkedissue) {
        setLinkedissue(linkedissue);
        return this;
    }
    // -- [affversion] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "AFFVERSION", nullable = false)
    public String getAffversion() {
        return affversion;
    }

    public void setAffversion(String affversion) {
        this.affversion = affversion;
    }

    public JiraTask affversion(String affversion) {
        setAffversion(affversion);
        return this;
    }
    // -- [targetversion] ------------------------

    @Size(max = 255)
    @Column(name = "TARGETVERSION")
    public String getTargetversion() {
        return targetversion;
    }

    public void setTargetversion(String targetversion) {
        this.targetversion = targetversion;
    }

    public JiraTask targetversion(String targetversion) {
        setTargetversion(targetversion);
        return this;
    }
    // -- [deliveryversion] ------------------------

    @Size(max = 255)
    @Column(name = "DELIVERYVERSION")
    public String getDeliveryversion() {
        return deliveryversion;
    }

    public void setDeliveryversion(String deliveryversion) {
        this.deliveryversion = deliveryversion;
    }

    public JiraTask deliveryversion(String deliveryversion) {
        setDeliveryversion(deliveryversion);
        return this;
    }
    // -- [projectId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "PROJECT_ID", precision = 10)
    public Integer getProjectId() {
        return projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public JiraTask projectId(Integer projectId) {
        setProjectId(projectId);
        return this;
    }
    // -- [versionId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "VERSION_ID", precision = 10)
    public Integer getVersionId() {
        return versionId;
    }

    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    public JiraTask versionId(Integer versionId) {
        setVersionId(versionId);
        return this;
    }
    // -- [subProjectId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "SUB_PROJECT_ID", precision = 10)
    public Integer getSubProjectId() {
        return subProjectId;
    }

    public void setSubProjectId(Integer subProjectId) {
        this.subProjectId = subProjectId;
    }

    public JiraTask subProjectId(Integer subProjectId) {
        setSubProjectId(subProjectId);
        return this;
    }
    // -- [subVersionId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "SUB_VERSION_ID", precision = 10)
    public Integer getSubVersionId() {
        return subVersionId;
    }

    public void setSubVersionId(Integer subVersionId) {
        this.subVersionId = subVersionId;
    }

    public JiraTask subVersionId(Integer subVersionId) {
        setSubVersionId(subVersionId);
        return this;
    }
    // -- [taskTypeId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "TASK_TYPE_ID", precision = 10)
    public Integer getTaskTypeId() {
        return taskTypeId;
    }

    public void setTaskTypeId(Integer taskTypeId) {
        this.taskTypeId = taskTypeId;
    }

    public JiraTask taskTypeId(Integer taskTypeId) {
        setTaskTypeId(taskTypeId);
        return this;
    }
    // -- [taskId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "TASK_ID", precision = 10)
    public Integer getTaskId() {
        return taskId;
    }

    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    public JiraTask taskId(Integer taskId) {
        setTaskId(taskId);
        return this;
    }
    // -- [state] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "\"STATE\"", nullable = false)
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public JiraTask state(String state) {
        setState(state);
        return this;
    }
    // -- [warning] ------------------------

    @Size(max = 255)
    @Column(name = "WARNING")
    public String getWarning() {
        return warning;
    }

    public void setWarning(String warning) {
        this.warning = warning;
    }

    public JiraTask warning(String warning) {
        setWarning(warning);
        return this;
    }
    // -- [error] ------------------------

    @Size(max = 255)
    @Column(name = "ERROR")
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public JiraTask error(String error) {
        setError(error);
        return this;
    }

    /**
     * Apply the default values.
     */
    public JiraTask withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof JiraTask && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this JiraTask instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("projectname", getProjectname()) //
                .add("ident", getIdent()) //
                .add("issuetype", getIssuetype()) //
                .add("summary", getSummary()) //
                .add("severity", getSeverity()) //
                .add("status", getStatus()) //
                .add("priority", getPriority()) //
                .add("assignee", getAssignee()) //
                .add("reporter", getReporter()) //
                .add("components", getComponents()) //
                .add("linkedissue", getLinkedissue()) //
                .add("affversion", getAffversion()) //
                .add("targetversion", getTargetversion()) //
                .add("deliveryversion", getDeliveryversion()) //
                .add("projectId", getProjectId()) //
                .add("versionId", getVersionId()) //
                .add("subProjectId", getSubProjectId()) //
                .add("subVersionId", getSubVersionId()) //
                .add("taskTypeId", getTaskTypeId()) //
                .add("taskId", getTaskId()) //
                .add("state", getState()) //
                .add("warning", getWarning()) //
                .add("error", getError()) //
                .toString();
    }
}