/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.apside.gismo.domain;

import static javax.persistence.EnumType.STRING;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "PROFIL")
public class Profil implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Profil.class.getName());

    // Raw attributes
    private Integer id;
    private ProfileType type;
    private Integer userId;
    private Integer projectGroupId;
    private Integer projectId;

    @Override
    public String entityClassName() {
        return Profil.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "ID", precision = 10)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Profil id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [type] ------------------------

    @NotNull
    @Column(name = "\"TYPE\"", nullable = false, length = 20)
    @Enumerated(STRING)
    public ProfileType getType() {
        return type;
    }

    public void setType(ProfileType type) {
        this.type = type;
    }

    public Profil type(ProfileType type) {
        setType(type);
        return this;
    }
    // -- [userId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "USER_ID", nullable = false, precision = 10)
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Profil userId(Integer userId) {
        setUserId(userId);
        return this;
    }
    // -- [projectGroupId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "PROJECT_GROUP_ID", precision = 10)
    public Integer getProjectGroupId() {
        return projectGroupId;
    }

    public void setProjectGroupId(Integer projectGroupId) {
        this.projectGroupId = projectGroupId;
    }

    public Profil projectGroupId(Integer projectGroupId) {
        setProjectGroupId(projectGroupId);
        return this;
    }
    // -- [projectId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "PROJECT_ID", precision = 10)
    public Integer getProjectId() {
        return projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public Profil projectId(Integer projectId) {
        setProjectId(projectId);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Profil withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Profil && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Profil instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("type", getType()) //
                .add("userId", getUserId()) //
                .add("projectGroupId", getProjectGroupId()) //
                .add("projectId", getProjectId()) //
                .toString();
    }
}