/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ProjectGroup.class)
public abstract class ProjectGroup_ {

    // Raw attributes
    public static volatile SingularAttribute<ProjectGroup, Integer> id;
    public static volatile SingularAttribute<ProjectGroup, String> name;
}