/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SubVersion.class)
public abstract class SubVersion_ {

    // Raw attributes
    public static volatile SingularAttribute<SubVersion, Integer> id;
    public static volatile SingularAttribute<SubVersion, String> name;
    public static volatile SingularAttribute<SubVersion, Integer> subProjectId;
    public static volatile SingularAttribute<SubVersion, Integer> versionId;
}