/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Task.class)
public abstract class Task_ {

    // Raw attributes
    public static volatile SingularAttribute<Task, Integer> id;
    public static volatile SingularAttribute<Task, String> externalId;
    public static volatile SingularAttribute<Task, String> name;
    public static volatile SingularAttribute<Task, Integer> taskTypeId;
    public static volatile SingularAttribute<Task, TaskLevel> level;
    public static volatile SingularAttribute<Task, Integer> projectId;
    public static volatile SingularAttribute<Task, Integer> versionId;
    public static volatile SingularAttribute<Task, Integer> subProjectId;
    public static volatile SingularAttribute<Task, Integer> subVersionId;
    public static volatile SingularAttribute<Task, TaskStatus> state;
    public static volatile SingularAttribute<Task, Integer> consumedtime;
    public static volatile SingularAttribute<Task, Integer> previewtime;
    public static volatile SingularAttribute<Task, Integer> remaintime;
    public static volatile SingularAttribute<Task, Integer> isguarantee;
}