/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Enum.java.enum.vm
 */
package com.apside.gismo.domain;

public enum WeekDay {
    Monday, //
    Tuesday, //
    Wednesday, //
    Thursday, //
    Friday, //
    Saturday, //
    Sunday;
}