/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.apside.gismo.domain;

import java.time.LocalDate;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(WeekNumber.class)
public abstract class WeekNumber_ {

    // Raw attributes
    public static volatile SingularAttribute<WeekNumber, Integer> id;
    public static volatile SingularAttribute<WeekNumber, Integer> dateyear;
    public static volatile SingularAttribute<WeekNumber, Integer> dateweek;
    public static volatile SingularAttribute<WeekNumber, WeekDay> dateday;
    public static volatile SingularAttribute<WeekNumber, LocalDate> date;
}