/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.apside.gismo.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for CapitalItem.
 */
public class CapitalItemDTO {
    public Integer id;
    public String name;
    public String subprojectName;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}