/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.apside.gismo.dto;

import java.util.List;
import java.util.stream.Collectors;

import javax.inject.Inject;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.apside.gismo.domain.CapitalItem;
import com.apside.gismo.domain.CapitalItem_;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.CapitalItemRepository;

/**
 * A simple DTO Facility for CapitalItem.
 */
@Service
public class CapitalItemDTOService {

    @Inject
    private CapitalItemRepository capitalItemRepository;

    @Transactional(readOnly = true)
    public CapitalItemDTO findOne(Integer id) {
        return toDTO(capitalItemRepository.findOne(id));
    }

    @Transactional(readOnly = true)
    public List<CapitalItemDTO> complete(String query, int maxResults) {
        List<CapitalItem> results = capitalItemRepository.complete(query, maxResults);
        return results.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public PageResponse<CapitalItemDTO> findAll(PageRequestByExample<CapitalItemDTO> req) {
        Example<CapitalItem> example = null;
        CapitalItem capitalItem = toEntity(req.example);

        if (capitalItem != null) {
            ExampleMatcher matcher = ExampleMatcher.matching() //
                    .withMatcher(CapitalItem_.name.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CapitalItem_.subprojectName.getName(), match -> match.ignoreCase().startsWith());

            example = Example.of(capitalItem, matcher);
        }

        Page<CapitalItem> page;
        if (example != null) {
            page = capitalItemRepository.findAll(example, req.toPageable());
        } else {
            page = capitalItemRepository.findAll(req.toPageable());
        }

        List<CapitalItemDTO> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    @Transactional
    public CapitalItemDTO save(CapitalItemDTO dto) {
        if (dto == null) {
            return null;
        }

        final CapitalItem capitalItem;

        if (dto.isIdSet()) {
            CapitalItem capitalItemTmp = capitalItemRepository.findOne(dto.id);
            if (capitalItemTmp != null) {
                capitalItem = capitalItemTmp;
            } else {
                capitalItem = new CapitalItem();
                capitalItem.setId(dto.id);
            }
        } else {
            capitalItem = new CapitalItem();
        }

        capitalItem.setName(dto.name);

        capitalItem.setSubprojectName(dto.subprojectName);

        return toDTO(capitalItemRepository.save(capitalItem));
    }

    /**
     * Converts the passed capitalItem to a DTO.
     */
    public CapitalItemDTO toDTO(CapitalItem capitalItem) {
        return toDTO(capitalItem, 1);
    }

    /**
     * Converts the passed capitalItem to a DTO. The depth is used to control the
     * amount of association you want. It also prevents potential infinite serialization cycles.
     *
     * @param capitalItem
     * @param depth the depth of the serialization. A depth equals to 0, means no x-to-one association will be serialized.
     *              A depth equals to 1 means that xToOne associations will be serialized. 2 means, xToOne associations of
     *              xToOne associations will be serialized, etc.
     */
    public CapitalItemDTO toDTO(CapitalItem capitalItem, int depth) {
        if (capitalItem == null) {
            return null;
        }

        CapitalItemDTO dto = new CapitalItemDTO();

        dto.id = capitalItem.getId();
        dto.name = capitalItem.getName();
        dto.subprojectName = capitalItem.getSubprojectName();
        if (depth-- > 0) {
        }

        return dto;
    }

    /**
     * Converts the passed dto to a CapitalItem.
     * Convenient for query by example.
     */
    public CapitalItem toEntity(CapitalItemDTO dto) {
        return toEntity(dto, 1);
    }

    /**
     * Converts the passed dto to a CapitalItem.
     * Convenient for query by example.
     */
    public CapitalItem toEntity(CapitalItemDTO dto, int depth) {
        if (dto == null) {
            return null;
        }

        CapitalItem capitalItem = new CapitalItem();

        capitalItem.setId(dto.id);
        capitalItem.setName(dto.name);
        capitalItem.setSubprojectName(dto.subprojectName);
        if (depth-- > 0) {
        }

        return capitalItem;
    }
}