/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.apside.gismo.dto;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for GismoImputation.
 */
public class GismoImputationDTO {
    public Integer id;
    public Integer taskId;
    public Integer userId;
    public LocalDate imputdate;
    public Integer imputtime;
    public String detail;
    public Integer weeknumberid;
    public String warning;
    public String error;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}