/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.apside.gismo.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for JiraTask.
 */
public class JiraTaskDTO {
    public Integer id;
    public String projectname;
    public String ident;
    public String issuetype;
    public String summary;
    public String severity;
    public String status;
    public String priority;
    public String assignee;
    public String reporter;
    public String components;
    public String linkedissue;
    public String affversion;
    public String targetversion;
    public String deliveryversion;
    public Integer projectId;
    public Integer versionId;
    public Integer subProjectId;
    public Integer subVersionId;
    public Integer taskTypeId;
    public Integer taskId;
    public String state;
    public String warning;
    public String error;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}