/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.apside.gismo.dto;

import com.apside.gismo.domain.ProfileType;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for Profil.
 */
public class ProfilDTO {
    public Integer id;
    public ProfileType type;
    public Integer userId;
    public Integer projectGroupId;
    public Integer projectId;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}