/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.apside.gismo.dto;

import com.apside.gismo.domain.TaskLevel;
import com.apside.gismo.domain.TaskStatus;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for Task.
 */
public class TaskDTO {
    public Integer id;
    public String externalId;
    public String name;
    public Integer taskTypeId;
    public TaskLevel level;
    public Integer projectId;
    public Integer versionId;
    public Integer subProjectId;
    public Integer subVersionId;
    public TaskStatus state;
    public Integer consumedtime;
    public Integer previewtime;
    public Integer remaintime;
    public Integer isguarantee;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}