/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.apside.gismo.dto;

import java.util.List;
import java.util.stream.Collectors;

import javax.inject.Inject;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.apside.gismo.domain.Version;
import com.apside.gismo.domain.Version_;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.VersionRepository;

/**
 * A simple DTO Facility for Version.
 */
@Service
public class VersionDTOService {

    @Inject
    private VersionRepository versionRepository;

    @Transactional(readOnly = true)
    public VersionDTO findOne(Integer id) {
        return toDTO(versionRepository.findOne(id));
    }

    @Transactional(readOnly = true)
    public List<VersionDTO> complete(String query, int maxResults) {
        List<Version> results = versionRepository.complete(query, maxResults);
        return results.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public PageResponse<VersionDTO> findAll(PageRequestByExample<VersionDTO> req) {
        Example<Version> example = null;
        Version version = toEntity(req.example);

        if (version != null) {
            ExampleMatcher matcher = ExampleMatcher.matching() //
                    .withMatcher(Version_.name.getName(), match -> match.ignoreCase().startsWith());

            example = Example.of(version, matcher);
        }

        Page<Version> page;
        if (example != null) {
            page = versionRepository.findAll(example, req.toPageable());
        } else {
            page = versionRepository.findAll(req.toPageable());
        }

        List<VersionDTO> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    @Transactional
    public VersionDTO save(VersionDTO dto) {
        if (dto == null) {
            return null;
        }

        final Version version;

        if (dto.isIdSet()) {
            Version versionTmp = versionRepository.findOne(dto.id);
            if (versionTmp != null) {
                version = versionTmp;
            } else {
                version = new Version();
                version.setId(dto.id);
            }
        } else {
            version = new Version();
        }

        version.setName(dto.name);

        version.setProjectId(dto.projectId);

        return toDTO(versionRepository.save(version));
    }

    /**
     * Converts the passed version to a DTO.
     */
    public VersionDTO toDTO(Version version) {
        return toDTO(version, 1);
    }

    /**
     * Converts the passed version to a DTO. The depth is used to control the
     * amount of association you want. It also prevents potential infinite serialization cycles.
     *
     * @param version
     * @param depth the depth of the serialization. A depth equals to 0, means no x-to-one association will be serialized.
     *              A depth equals to 1 means that xToOne associations will be serialized. 2 means, xToOne associations of
     *              xToOne associations will be serialized, etc.
     */
    public VersionDTO toDTO(Version version, int depth) {
        if (version == null) {
            return null;
        }

        VersionDTO dto = new VersionDTO();

        dto.id = version.getId();
        dto.name = version.getName();
        dto.projectId = version.getProjectId();
        if (depth-- > 0) {
        }

        return dto;
    }

    /**
     * Converts the passed dto to a Version.
     * Convenient for query by example.
     */
    public Version toEntity(VersionDTO dto) {
        return toEntity(dto, 1);
    }

    /**
     * Converts the passed dto to a Version.
     * Convenient for query by example.
     */
    public Version toEntity(VersionDTO dto, int depth) {
        if (dto == null) {
            return null;
        }

        Version version = new Version();

        version.setId(dto.id);
        version.setName(dto.name);
        version.setProjectId(dto.projectId);
        if (depth-- > 0) {
        }

        return version;
    }
}