/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.apside.gismo.dto;

import java.util.List;
import java.util.stream.Collectors;

import javax.inject.Inject;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.apside.gismo.domain.WeekNumber;
import com.apside.gismo.domain.WeekNumber_;
import com.apside.gismo.dto.support.PageRequestByExample;
import com.apside.gismo.dto.support.PageResponse;
import com.apside.gismo.repository.WeekNumberRepository;

/**
 * A simple DTO Facility for WeekNumber.
 */
@Service
public class WeekNumberDTOService {

    @Inject
    private WeekNumberRepository weekNumberRepository;

    @Transactional(readOnly = true)
    public WeekNumberDTO findOne(Integer id) {
        return toDTO(weekNumberRepository.findOne(id));
    }

    @Transactional(readOnly = true)
    public List<WeekNumberDTO> complete(String query, int maxResults) {
        List<WeekNumber> results = weekNumberRepository.complete(query, maxResults);
        return results.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public PageResponse<WeekNumberDTO> findAll(PageRequestByExample<WeekNumberDTO> req) {
        Example<WeekNumber> example = null;
        WeekNumber weekNumber = toEntity(req.example);

        if (weekNumber != null) {
            ExampleMatcher matcher = ExampleMatcher.matching() //
            ;

            example = Example.of(weekNumber, matcher);
        }

        Page<WeekNumber> page;
        if (example != null) {
            page = weekNumberRepository.findAll(example, req.toPageable());
        } else {
            page = weekNumberRepository.findAll(req.toPageable());
        }

        List<WeekNumberDTO> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    @Transactional
    public WeekNumberDTO save(WeekNumberDTO dto) {
        if (dto == null) {
            return null;
        }

        final WeekNumber weekNumber;

        if (dto.isIdSet()) {
            WeekNumber weekNumberTmp = weekNumberRepository.findOne(dto.id);
            if (weekNumberTmp != null) {
                weekNumber = weekNumberTmp;
            } else {
                weekNumber = new WeekNumber();
                weekNumber.setId(dto.id);
            }
        } else {
            weekNumber = new WeekNumber();
        }

        weekNumber.setDateyear(dto.dateyear);

        weekNumber.setDateweek(dto.dateweek);

        weekNumber.setDateday(dto.dateday);

        weekNumber.setDate(dto.date);

        return toDTO(weekNumberRepository.save(weekNumber));
    }

    /**
     * Converts the passed weekNumber to a DTO.
     */
    public WeekNumberDTO toDTO(WeekNumber weekNumber) {
        return toDTO(weekNumber, 1);
    }

    /**
     * Converts the passed weekNumber to a DTO. The depth is used to control the
     * amount of association you want. It also prevents potential infinite serialization cycles.
     *
     * @param weekNumber
     * @param depth the depth of the serialization. A depth equals to 0, means no x-to-one association will be serialized.
     *              A depth equals to 1 means that xToOne associations will be serialized. 2 means, xToOne associations of
     *              xToOne associations will be serialized, etc.
     */
    public WeekNumberDTO toDTO(WeekNumber weekNumber, int depth) {
        if (weekNumber == null) {
            return null;
        }

        WeekNumberDTO dto = new WeekNumberDTO();

        dto.id = weekNumber.getId();
        dto.dateyear = weekNumber.getDateyear();
        dto.dateweek = weekNumber.getDateweek();
        dto.dateday = weekNumber.getDateday();
        dto.date = weekNumber.getDate();
        if (depth-- > 0) {
        }

        return dto;
    }

    /**
     * Converts the passed dto to a WeekNumber.
     * Convenient for query by example.
     */
    public WeekNumber toEntity(WeekNumberDTO dto) {
        return toEntity(dto, 1);
    }

    /**
     * Converts the passed dto to a WeekNumber.
     * Convenient for query by example.
     */
    public WeekNumber toEntity(WeekNumberDTO dto, int depth) {
        if (dto == null) {
            return null;
        }

        WeekNumber weekNumber = new WeekNumber();

        weekNumber.setId(dto.id);
        weekNumber.setDateyear(dto.dateyear);
        weekNumber.setDateweek(dto.dateweek);
        weekNumber.setDateday(dto.dateday);
        weekNumber.setDate(dto.date);
        if (depth-- > 0) {
        }

        return weekNumber;
    }
}