/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.apside.gismo.dto;

import java.time.LocalDate;

import com.apside.gismo.domain.WeekDay;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for WeekNumber.
 */
public class WeekNumberDTO {
    public Integer id;
    public Integer dateyear;
    public Integer dateweek;
    public WeekDay dateday;
    public LocalDate date;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}