//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { JiraTaskType } from './jiraTaskType';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class JiraTaskTypeService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a JiraTaskType by id.
     */
    getJiraTaskType(id : any) : Observable<JiraTaskType> {
        return this.http.get('/api/jiraTaskTypes/' + id)
            .pipe(
                map(response => new JiraTaskType(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed jiraTaskType.
     */
    update(jiraTaskType : JiraTaskType) : Observable<JiraTaskType> {
        let body = jiraTaskType;

        return this.http.put('/api/jiraTaskTypes/', body)
            .pipe(
                map(response => new JiraTaskType(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of JiraTaskType using the passed
     * jiraTaskType as an example for the search by example facility.
     */
    getPage(jiraTaskType : JiraTaskType, event : LazyLoadEvent) : Observable<PageResponse<JiraTaskType>> {
        let req = new PageRequestByExample(jiraTaskType, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/jiraTaskTypes/page', body)
            .pipe(
                map(pr =>  new PageResponse<JiraTaskType>(pr.totalPages, pr.totalElements, JiraTaskType.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by JiraTaskTypeCompleteComponent.
     */
    complete(query : string) : Observable<JiraTaskType[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/jiraTaskTypes/complete', body)
            .pipe(
                map(response => JiraTaskType.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an JiraTaskType by id.
     */
    delete(id : any) {
        return this.http.delete('/api/jiraTaskTypes/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
