//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {JiraTaskType} from './jiraTaskType';
import {JiraTaskTypeService} from './jiraTaskType.service';

@Component({
    moduleId: module.id,
	templateUrl: 'jiraTaskType-detail.component.html',
	selector: 'jiraTaskType-detail',
})
export class JiraTaskTypeDetailComponent implements OnInit, OnDestroy {
    jiraTaskType : JiraTaskType;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<JiraTaskType>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private jiraTaskTypeService: JiraTaskTypeService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for jiraTaskType-detail ' + id);

            if (id === 'new') {
                this.jiraTaskType = new JiraTaskType();
            } else {
                this.jiraTaskTypeService.getJiraTaskType(id)
                    .subscribe(jiraTaskType => {
                            this.jiraTaskType = jiraTaskType;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.jiraTaskTypeService.update(this.jiraTaskType).
            subscribe(
                jiraTaskType => {
                    this.jiraTaskType = jiraTaskType;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.jiraTaskType);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
