//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges} from '@angular/core';
import { Router } from '@angular/router';
import { UnderConst } from './under_const.component';

@Component({
    moduleId: module.id,
    templateUrl: 'under_const.component.html',
    selector: 'under_const'
})
export class UnderConstComponent {

    constructor(private router: Router) {
    }

}
