//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { CapitalImputation } from './capitalImputation';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class CapitalImputationService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a CapitalImputation by id.
     */
    getCapitalImputation(id : any) : Observable<CapitalImputation> {
        return this.http.get('/api/capitalImputations/' + id)
            .pipe(
                map(response => new CapitalImputation(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed capitalImputation.
     */
    update(capitalImputation : CapitalImputation) : Observable<CapitalImputation> {
        let body = capitalImputation;

        return this.http.put('/api/capitalImputations/', body)
            .pipe(
                map(response => new CapitalImputation(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of CapitalImputation using the passed
     * capitalImputation as an example for the search by example facility.
     */
    getPage(capitalImputation : CapitalImputation, event : LazyLoadEvent) : Observable<PageResponse<CapitalImputation>> {
        let req = new PageRequestByExample(capitalImputation, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/capitalImputations/page', body)
            .pipe(
                map(pr =>  new PageResponse<CapitalImputation>(pr.totalPages, pr.totalElements, CapitalImputation.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by CapitalImputationCompleteComponent.
     */
    complete(query : string) : Observable<CapitalImputation[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/capitalImputations/complete', body)
            .pipe(
                map(response => CapitalImputation.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an CapitalImputation by id.
     */
    delete(id : any) {
        return this.http.delete('/api/capitalImputations/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
