//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {CapitalImputation} from './capitalImputation';
import {CapitalImputationService} from './capitalImputation.service';

@Component({
    moduleId: module.id,
	templateUrl: 'capitalImputation-detail.component.html',
	selector: 'capitalImputation-detail',
})
export class CapitalImputationDetailComponent implements OnInit, OnDestroy {
    capitalImputation : CapitalImputation;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<CapitalImputation>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private capitalImputationService: CapitalImputationService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for capitalImputation-detail ' + id);

            if (id === 'new') {
                this.capitalImputation = new CapitalImputation();
            } else {
                this.capitalImputationService.getCapitalImputation(id)
                    .subscribe(capitalImputation => {
                            this.capitalImputation = capitalImputation;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.capitalImputationService.update(this.capitalImputation).
            subscribe(
                capitalImputation => {
                    this.capitalImputation = capitalImputation;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.capitalImputation);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
