//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {TaskLink} from './taskLink';
import {TaskLinkService} from './taskLink.service';

@Component({
    moduleId: module.id,
	templateUrl: 'taskLink-detail.component.html',
	selector: 'taskLink-detail',
})
export class TaskLinkDetailComponent implements OnInit, OnDestroy {
    taskLink : TaskLink;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<TaskLink>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private taskLinkService: TaskLinkService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for taskLink-detail ' + id);

            if (id === 'new') {
                this.taskLink = new TaskLink();
            } else {
                this.taskLinkService.getTaskLink(id)
                    .subscribe(taskLink => {
                            this.taskLink = taskLink;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.taskLinkService.update(this.taskLink).
            subscribe(
                taskLink => {
                    this.taskLink = taskLink;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.taskLink);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
