//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {TaskLinkPk} from "./taskLinkPk";

export class TaskLink {
    id : TaskLinkPk = new TaskLinkPk();


    constructor(json? : any) {
        if (json != null) {
            this.id = new TaskLinkPk(json.id);
        }
    }

    // Utils

    static toArray(jsons : any[]) : TaskLink[] {
        let taskLinks : TaskLink[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                taskLinks.push(new TaskLink(json));
            }
        }
        return taskLinks;
    }
}
