//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class CapitalItem {
    // Raw attributes
    id : number;
    name : string;
    subprojectName : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.name = json.name;
            this.subprojectName = json.subprojectName;
        }
    }

    // Utils

    static toArray(jsons : any[]) : CapitalItem[] {
        let capitalItems : CapitalItem[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                capitalItems.push(new CapitalItem(json));
            }
        }
        return capitalItems;
    }
}
