/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.apside.gismo.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.apside.gismo.domain.JiraTask;
import com.apside.gismo.domain.JiraTask_;

public interface JiraTaskRepository extends JpaRepository<JiraTask, Integer> {

    default List<JiraTask> complete(String query, int maxResults) {
        JiraTask probe = new JiraTask();
        probe.setProjectname(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(JiraTask_.projectname.getName(), match -> match.ignoreCase().startsWith());

        Page<JiraTask> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}