/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.apside.gismo.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.apside.gismo.domain.Profil;
import com.apside.gismo.domain.Profil_;

public interface ProfilRepository extends JpaRepository<Profil, Integer> {

    default List<Profil> complete(String query, int maxResults) {
        Profil probe = new Profil();

        ExampleMatcher matcher = ExampleMatcher.matching() //
        ;

        Page<Profil> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}